-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rrt_FloatToFixed_16ul_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of rrt_FloatToFixed_16ul_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_47800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000111100000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv64_3FE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_BFE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";

attribute shreg_extract : string;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln7_fu_99_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_267_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_272_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_71_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_277 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_277_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_277_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_277_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_62_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_282 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_68_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal conv_reg_287 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln7_fu_120_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln7_reg_292 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_77_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal dc_reg_297 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_s_reg_302 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_302_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_149_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_45_reg_307 : STD_LOGIC_VECTOR (51 downto 0);
    signal isNeg_fu_163_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_181_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ush_reg_317 : STD_LOGIC_VECTOR (11 downto 0);
    signal val_fu_243_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_322 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bitcast_ln7_fu_81_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_85_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln7_fu_95_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln7_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_fu_115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_fu_128_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_44_fu_139_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln513_fu_153_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln513_fu_157_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1364_fu_171_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1364_fu_177_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mantissa_fu_189_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln1340_fu_202_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_198_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln1340_fu_205_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_fu_209_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_fu_221_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_12_fu_215_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln671_fu_229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_233_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_23_fu_250_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_62_ce : STD_LOGIC;
    signal grp_fu_68_ce : STD_LOGIC;
    signal grp_fu_71_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal grp_fu_77_ce : STD_LOGIC;
    signal result_V_fu_255_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal d_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);

    component rrt_fmul_32ns_32ns_32_5_max_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_fpext_32ns_64_2_no_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rrt_fcmp_32ns_32ns_1_3_no_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component rrt_dadd_64ns_64ns_64_12_full_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    fmul_32ns_32ns_32_5_max_dsp_0_U1 : component rrt_fmul_32ns_32ns_32_5_max_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => d_int_reg,
        din1 => ap_const_lv32_47800000,
        ce => grp_fu_62_ce,
        dout => grp_fu_62_p2);

    fpext_32ns_64_2_no_dsp_0_U2 : component rrt_fpext_32ns_64_2_no_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_reg_282,
        ce => grp_fu_68_ce,
        dout => grp_fu_68_p1);

    fcmp_32ns_32ns_1_3_no_dsp_0_U3 : component rrt_fcmp_32ns_32ns_1_3_no_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => d_int_reg,
        din1 => ap_const_lv32_0,
        ce => grp_fu_71_ce,
        opcode => ap_const_lv5_3,
        dout => grp_fu_71_p2);

    dadd_64ns_64ns_64_12_full_dsp_0_U4 : component rrt_dadd_64ns_64ns_64_12_full_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => conv_reg_287,
        din1 => select_ln7_reg_292,
        ce => grp_fu_77_ce,
        dout => grp_fu_77_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= result_V_fu_255_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                conv_reg_287 <= grp_fu_68_p1;
                dc_reg_297 <= grp_fu_77_p2;
                icmp_ln7_2_reg_272 <= icmp_ln7_2_fu_105_p2;
                icmp_ln7_2_reg_272_pp0_iter1_reg <= icmp_ln7_2_reg_272;
                icmp_ln7_2_reg_272_pp0_iter2_reg <= icmp_ln7_2_reg_272_pp0_iter1_reg;
                icmp_ln7_2_reg_272_pp0_iter3_reg <= icmp_ln7_2_reg_272_pp0_iter2_reg;
                icmp_ln7_2_reg_272_pp0_iter4_reg <= icmp_ln7_2_reg_272_pp0_iter3_reg;
                icmp_ln7_2_reg_272_pp0_iter5_reg <= icmp_ln7_2_reg_272_pp0_iter4_reg;
                icmp_ln7_reg_267 <= icmp_ln7_fu_99_p2;
                icmp_ln7_reg_267_pp0_iter1_reg <= icmp_ln7_reg_267;
                icmp_ln7_reg_267_pp0_iter2_reg <= icmp_ln7_reg_267_pp0_iter1_reg;
                icmp_ln7_reg_267_pp0_iter3_reg <= icmp_ln7_reg_267_pp0_iter2_reg;
                icmp_ln7_reg_267_pp0_iter4_reg <= icmp_ln7_reg_267_pp0_iter3_reg;
                icmp_ln7_reg_267_pp0_iter5_reg <= icmp_ln7_reg_267_pp0_iter4_reg;
                isNeg_reg_312 <= add_ln513_fu_157_p2(11 downto 11);
                mul_reg_282 <= grp_fu_62_p2;
                p_Result_s_reg_302 <= data_V_fu_128_p1(63 downto 63);
                p_Result_s_reg_302_pp0_iter20_reg <= p_Result_s_reg_302;
                    select_ln7_reg_292(63) <= select_ln7_fu_120_p3(63);
                tmp_3_reg_277 <= grp_fu_71_p2;
                tmp_3_reg_277_pp0_iter3_reg <= tmp_3_reg_277;
                tmp_3_reg_277_pp0_iter4_reg <= tmp_3_reg_277_pp0_iter3_reg;
                tmp_3_reg_277_pp0_iter5_reg <= tmp_3_reg_277_pp0_iter4_reg;
                tmp_45_reg_307 <= tmp_45_fu_149_p1;
                ush_reg_317 <= ush_fu_181_p3;
                val_reg_322 <= val_fu_243_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                d_int_reg <= d;
            end if;
        end if;
    end process;
    select_ln7_reg_292(62 downto 0) <= "011111111100000000000000000000000000000000000000000000000000000";
    add_ln513_fu_157_p2 <= std_logic_vector(unsigned(zext_ln513_fu_153_p1) + unsigned(ap_const_lv12_C01));
    and_ln7_fu_115_p2 <= (tmp_3_reg_277_pp0_iter5_reg and or_ln7_fu_111_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(result_V_fu_255_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= result_V_fu_255_p3;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bitcast_ln7_fu_81_p1 <= d_int_reg;
    data_V_fu_128_p1 <= dc_reg_297;

    grp_fu_62_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_62_ce <= ap_const_logic_1;
        else 
            grp_fu_62_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_68_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_68_ce <= ap_const_logic_1;
        else 
            grp_fu_68_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_71_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_71_ce <= ap_const_logic_1;
        else 
            grp_fu_71_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_77_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_77_ce <= ap_const_logic_1;
        else 
            grp_fu_77_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln7_2_fu_105_p2 <= "1" when (trunc_ln7_fu_95_p1 = ap_const_lv23_0) else "0";
    icmp_ln7_fu_99_p2 <= "0" when (tmp_s_fu_85_p4 = ap_const_lv8_FF) else "1";
    isNeg_fu_163_p3 <= add_ln513_fu_157_p2(11 downto 11);
    mantissa_fu_189_p4 <= ((ap_const_lv1_1 & tmp_45_reg_307) & ap_const_lv1_0);
    or_ln7_fu_111_p2 <= (icmp_ln7_reg_267_pp0_iter5_reg or icmp_ln7_2_reg_272_pp0_iter5_reg);
    r_V_12_fu_215_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_198_p1),to_integer(unsigned('0' & zext_ln1340_fu_205_p1(31-1 downto 0)))));
    r_V_fu_209_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_198_p1),to_integer(unsigned('0' & zext_ln1340_fu_205_p1(31-1 downto 0)))));
    result_V_23_fu_250_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_322));
    result_V_fu_255_p3 <= 
        result_V_23_fu_250_p2 when (p_Result_s_reg_302_pp0_iter20_reg(0) = '1') else 
        val_reg_322;
    select_ln7_fu_120_p3 <= 
        ap_const_lv64_3FE0000000000000 when (and_ln7_fu_115_p2(0) = '1') else 
        ap_const_lv64_BFE0000000000000;
        sext_ln1340_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_317),32));

        sext_ln1364_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_171_p2),12));

    sub_ln1364_fu_171_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(tmp_44_fu_139_p4));
    tmp_44_fu_139_p4 <= data_V_fu_128_p1(62 downto 52);
    tmp_45_fu_149_p1 <= data_V_fu_128_p1(52 - 1 downto 0);
    tmp_8_fu_233_p4 <= r_V_12_fu_215_p2(84 downto 53);
    tmp_fu_221_p3 <= r_V_fu_209_p2(53 downto 53);
    tmp_s_fu_85_p4 <= bitcast_ln7_fu_81_p1(30 downto 23);
    trunc_ln7_fu_95_p1 <= bitcast_ln7_fu_81_p1(23 - 1 downto 0);
    ush_fu_181_p3 <= 
        sext_ln1364_fu_177_p1 when (isNeg_fu_163_p3(0) = '1') else 
        add_ln513_fu_157_p2;
    val_fu_243_p3 <= 
        zext_ln671_fu_229_p1 when (isNeg_reg_312(0) = '1') else 
        tmp_8_fu_233_p4;
    zext_ln1340_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_202_p1),137));
    zext_ln15_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_189_p4),137));
    zext_ln513_fu_153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_44_fu_139_p4),12));
    zext_ln671_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_221_p3),32));
end behav;
