-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rrt_Nearhw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_near_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_near_ce0 : OUT STD_LOGIC;
    X_near_we0 : OUT STD_LOGIC;
    X_near_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    RRT_Star_Pos_0_0_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    RRT_Star_Pos_0_0_ce0 : OUT STD_LOGIC;
    RRT_Star_Pos_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    RRT_Star_Pos_0_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    RRT_Star_Pos_0_1_ce0 : OUT STD_LOGIC;
    RRT_Star_Pos_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    RRT_Star_Pos_1_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    RRT_Star_Pos_1_ce0 : OUT STD_LOGIC;
    RRT_Star_Pos_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    Squared_r_n : IN STD_LOGIC_VECTOR (31 downto 0);
    N : IN STD_LOGIC_VECTOR (13 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_537_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_537_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_537_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_537_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_537_p_ce : OUT STD_LOGIC;
    grp_fu_541_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_541_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_541_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_541_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_541_p_ce : OUT STD_LOGIC;
    grp_fu_550_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_550_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_550_p_ce : OUT STD_LOGIC;
    grp_fu_553_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_553_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_553_p_ce : OUT STD_LOGIC;
    grp_fu_1261_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1261_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1261_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_1261_p_ce : OUT STD_LOGIC;
    grp_fu_1271_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1271_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1271_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_1271_p_ce : OUT STD_LOGIC );
end;


architecture behav of rrt_Nearhw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal conv_i_i_reg_602 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv9_i_i_reg_607 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_cast_fu_211_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state8_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state31_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state32_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state33_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state34_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state35_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state36_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_state37_pp0_stage0_iter29 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln141_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_cast_reg_615_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter16_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter17_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter18_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter19_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter20_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter21_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter22_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter23_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter24_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter25_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_cast_reg_615_pp0_iter26_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal B_x_reg_630 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_y_reg_635 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_i_i_i_reg_640 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal conv_i2_i_i_reg_645 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_650 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_3_reg_655 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_reg_660 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_660_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_243_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_41_reg_665 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_fu_257_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_670 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_275_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_reg_675 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_3_reg_680 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_reg_680_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_304_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_43_reg_685 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_3_fu_318_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_3_reg_690 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_3_fu_336_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_3_reg_695 : STD_LOGIC_VECTOR (8 downto 0);
    signal val_fu_398_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_700 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_3_fu_459_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_3_reg_706 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_fu_471_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_reg_712 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_21_fu_482_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_21_reg_717 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln34_fu_488_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln34_6_fu_497_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln_reg_734 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_4_reg_739 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_fu_526_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_reg_744 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln149_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_reg_749 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_reg_749_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal RRT_Star_Pos_1_load_reg_758 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state8 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln151_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_78 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln141_fu_205_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_fu_82 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln152_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal X_near_count_0_fu_86 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal grp_fu_174_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_178_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_fu_222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_fu_233_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_fu_247_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln344_fu_251_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1364_fu_265_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1364_fu_271_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_V_3_fu_283_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_42_fu_294_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_2_fu_308_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln344_2_fu_312_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1364_2_fu_326_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1364_2_fu_332_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_fu_344_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1340_fu_357_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_353_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1340_fu_360_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_fu_364_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_fu_376_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_9_fu_370_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln671_fu_384_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_388_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal mantissa_2_fu_405_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1340_3_fu_418_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_2_fu_414_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1340_3_fu_421_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_10_fu_425_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_39_fu_437_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_11_fu_431_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln671_2_fu_445_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_449_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_17_fu_466_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_20_fu_477_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rrt_fsub_32ns_32ns_32_9_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_sitofp_32ns_32_7_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_mul_32s_32s_48_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;



begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state8);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    X_near_count_0_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                X_near_count_0_fu_86 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (icmp_ln149_reg_749_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                X_near_count_0_fu_86 <= add_ln152_fu_542_p2;
            end if; 
        end if;
    end process;

    empty_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                empty_fu_82 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (icmp_ln149_reg_749_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_fu_82 <= add_ln152_fu_542_p2;
            end if; 
        end if;
    end process;

    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_78 <= ap_const_lv14_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln141_fu_200_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_fu_78 <= add_ln141_fu_205_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                B_x_reg_630 <= RRT_Star_Pos_0_0_q0;
                B_y_reg_635 <= RRT_Star_Pos_0_1_q0;
                    i_cast_reg_615_pp0_iter1_reg(13 downto 0) <= i_cast_reg_615(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                D_reg_744 <= D_fu_526_p2;
                dc_3_reg_655 <= grp_fu_541_p_dout0;
                dc_reg_650 <= grp_fu_537_p_dout0;
                    i_cast_reg_615_pp0_iter10_reg(13 downto 0) <= i_cast_reg_615_pp0_iter9_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter11_reg(13 downto 0) <= i_cast_reg_615_pp0_iter10_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter12_reg(13 downto 0) <= i_cast_reg_615_pp0_iter11_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter13_reg(13 downto 0) <= i_cast_reg_615_pp0_iter12_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter14_reg(13 downto 0) <= i_cast_reg_615_pp0_iter13_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter15_reg(13 downto 0) <= i_cast_reg_615_pp0_iter14_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter16_reg(13 downto 0) <= i_cast_reg_615_pp0_iter15_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter17_reg(13 downto 0) <= i_cast_reg_615_pp0_iter16_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter18_reg(13 downto 0) <= i_cast_reg_615_pp0_iter17_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter19_reg(13 downto 0) <= i_cast_reg_615_pp0_iter18_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter20_reg(13 downto 0) <= i_cast_reg_615_pp0_iter19_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter21_reg(13 downto 0) <= i_cast_reg_615_pp0_iter20_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter22_reg(13 downto 0) <= i_cast_reg_615_pp0_iter21_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter23_reg(13 downto 0) <= i_cast_reg_615_pp0_iter22_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter24_reg(13 downto 0) <= i_cast_reg_615_pp0_iter23_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter25_reg(13 downto 0) <= i_cast_reg_615_pp0_iter24_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter26_reg(13 downto 0) <= i_cast_reg_615_pp0_iter25_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter2_reg(13 downto 0) <= i_cast_reg_615_pp0_iter1_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter3_reg(13 downto 0) <= i_cast_reg_615_pp0_iter2_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter4_reg(13 downto 0) <= i_cast_reg_615_pp0_iter3_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter5_reg(13 downto 0) <= i_cast_reg_615_pp0_iter4_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter6_reg(13 downto 0) <= i_cast_reg_615_pp0_iter5_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter7_reg(13 downto 0) <= i_cast_reg_615_pp0_iter6_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter8_reg(13 downto 0) <= i_cast_reg_615_pp0_iter7_reg(13 downto 0);
                    i_cast_reg_615_pp0_iter9_reg(13 downto 0) <= i_cast_reg_615_pp0_iter8_reg(13 downto 0);
                icmp_ln149_reg_749 <= icmp_ln149_fu_530_p2;
                icmp_ln149_reg_749_pp0_iter28_reg <= icmp_ln149_reg_749;
                isNeg_3_reg_690 <= add_ln344_2_fu_312_p2(8 downto 8);
                isNeg_reg_670 <= add_ln344_fu_251_p2(8 downto 8);
                p_Result_3_reg_680 <= data_V_3_fu_283_p1(31 downto 31);
                p_Result_3_reg_680_pp0_iter19_reg <= p_Result_3_reg_680;
                p_Result_s_reg_660 <= data_V_fu_222_p1(31 downto 31);
                p_Result_s_reg_660_pp0_iter19_reg <= p_Result_s_reg_660;
                result_V_21_reg_717 <= result_V_21_fu_482_p3;
                result_V_reg_712 <= result_V_fu_471_p3;
                tmp_41_reg_665 <= tmp_41_fu_243_p1;
                tmp_43_reg_685 <= tmp_43_fu_304_p1;
                trunc_ln34_4_reg_739 <= grp_fu_1271_p_dout0(47 downto 16);
                trunc_ln_reg_734 <= grp_fu_1261_p_dout0(47 downto 16);
                ush_3_reg_695 <= ush_3_fu_336_p3;
                ush_reg_675 <= ush_fu_275_p3;
                val_3_reg_706 <= val_3_fu_459_p3;
                val_reg_700 <= val_fu_398_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln149_reg_749 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                RRT_Star_Pos_1_load_reg_758 <= RRT_Star_Pos_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                conv9_i_i_reg_607 <= grp_fu_553_p_dout0;
                conv_i_i_reg_602 <= grp_fu_550_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                conv_i2_i_i_reg_645 <= grp_fu_553_p_dout0;
                conv_i_i_i_reg_640 <= grp_fu_550_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln141_fu_200_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    i_cast_reg_615(13 downto 0) <= i_cast_fu_211_p1(13 downto 0);
            end if;
        end if;
    end process;
    i_cast_reg_615(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter1_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter2_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter3_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter4_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter5_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter6_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter7_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter8_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter9_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter10_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter11_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter12_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter13_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter14_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter15_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter16_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter17_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter18_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter19_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter20_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter21_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter22_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter23_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter24_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter25_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    i_cast_reg_615_pp0_iter26_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln141_fu_200_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln141_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln141_fu_200_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state38;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    D_fu_526_p2 <= std_logic_vector(unsigned(trunc_ln34_4_reg_739) + unsigned(trunc_ln_reg_734));
    RRT_Star_Pos_0_0_address0 <= i_cast_fu_211_p1(14 - 1 downto 0);

    RRT_Star_Pos_0_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            RRT_Star_Pos_0_0_ce0 <= ap_const_logic_1;
        else 
            RRT_Star_Pos_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    RRT_Star_Pos_0_1_address0 <= i_cast_fu_211_p1(14 - 1 downto 0);

    RRT_Star_Pos_0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            RRT_Star_Pos_0_1_ce0 <= ap_const_logic_1;
        else 
            RRT_Star_Pos_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    RRT_Star_Pos_1_address0 <= i_cast_reg_615_pp0_iter26_reg(14 - 1 downto 0);

    RRT_Star_Pos_1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter27)
    begin
        if (((ap_enable_reg_pp0_iter27 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            RRT_Star_Pos_1_ce0 <= ap_const_logic_1;
        else 
            RRT_Star_Pos_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    X_near_address0 <= zext_ln151_fu_537_p1(10 - 1 downto 0);

    X_near_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter29)
    begin
        if (((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            X_near_ce0 <= ap_const_logic_1;
        else 
            X_near_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    X_near_d0 <= RRT_Star_Pos_1_load_reg_758;

    X_near_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln149_reg_749_pp0_iter28_reg, ap_enable_reg_pp0_iter29)
    begin
        if (((ap_enable_reg_pp0_iter29 = ap_const_logic_1) and (icmp_ln149_reg_749_pp0_iter28_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            X_near_we0 <= ap_const_logic_1;
        else 
            X_near_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln141_fu_205_p2 <= std_logic_vector(unsigned(i_fu_78) + unsigned(ap_const_lv14_1));
    add_ln152_fu_542_p2 <= std_logic_vector(unsigned(empty_fu_82) + unsigned(ap_const_lv32_1));
    add_ln344_2_fu_312_p2 <= std_logic_vector(unsigned(zext_ln344_2_fu_308_p1) + unsigned(ap_const_lv9_181));
    add_ln344_fu_251_p2 <= std_logic_vector(unsigned(zext_ln344_fu_247_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state38 <= ap_CS_fsm(8);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state33_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state34_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state35_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state36_pp0_stage0_iter28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state37_pp0_stage0_iter29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state8_assign_proc : process(icmp_ln141_fu_200_p2)
    begin
        if ((icmp_ln141_fu_200_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29)
    begin
        if (((ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0) and (ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= X_near_count_0_fu_86;
    data_V_3_fu_283_p1 <= dc_3_reg_655;
    data_V_fu_222_p1 <= dc_reg_650;
    grp_fu_1261_p_ce <= ap_const_logic_1;
    grp_fu_1261_p_din0 <= sext_ln34_fu_488_p1(32 - 1 downto 0);
    grp_fu_1261_p_din1 <= sext_ln34_fu_488_p1(32 - 1 downto 0);
    grp_fu_1271_p_ce <= ap_const_logic_1;
    grp_fu_1271_p_din0 <= sext_ln34_6_fu_497_p1(32 - 1 downto 0);
    grp_fu_1271_p_din1 <= sext_ln34_6_fu_497_p1(32 - 1 downto 0);

    grp_fu_174_p0_assign_proc : process(ap_CS_fsm_state1, p_read, B_x_reg_630, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            grp_fu_174_p0 <= B_x_reg_630;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_174_p0 <= p_read;
        else 
            grp_fu_174_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_178_p0_assign_proc : process(ap_CS_fsm_state1, p_read1, B_y_reg_635, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            grp_fu_178_p0 <= B_y_reg_635;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_178_p0 <= p_read1;
        else 
            grp_fu_178_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_537_p_ce <= ap_const_logic_1;
    grp_fu_537_p_din0 <= conv_i_i_reg_602;
    grp_fu_537_p_din1 <= conv_i_i_i_reg_640;
    grp_fu_537_p_opcode <= ap_const_lv2_1;
    grp_fu_541_p_ce <= ap_const_logic_1;
    grp_fu_541_p_din0 <= conv9_i_i_reg_607;
    grp_fu_541_p_din1 <= conv_i2_i_i_reg_645;
    grp_fu_541_p_opcode <= ap_const_lv2_1;
    grp_fu_550_p_ce <= ap_const_logic_1;
    grp_fu_550_p_din0 <= grp_fu_174_p0;
    grp_fu_553_p_ce <= ap_const_logic_1;
    grp_fu_553_p_din0 <= grp_fu_178_p0;
    i_cast_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_78),64));
    icmp_ln141_fu_200_p2 <= "1" when (i_fu_78 = N) else "0";
    icmp_ln149_fu_530_p2 <= "1" when (signed(D_reg_744) < signed(Squared_r_n)) else "0";
    isNeg_3_fu_318_p3 <= add_ln344_2_fu_312_p2(8 downto 8);
    isNeg_fu_257_p3 <= add_ln344_fu_251_p2(8 downto 8);
    mantissa_2_fu_405_p4 <= ((ap_const_lv1_1 & tmp_43_reg_685) & ap_const_lv1_0);
    mantissa_fu_344_p4 <= ((ap_const_lv1_1 & tmp_41_reg_665) & ap_const_lv1_0);
    r_V_10_fu_425_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_2_fu_414_p1),to_integer(unsigned('0' & zext_ln1340_3_fu_421_p1(31-1 downto 0)))));
    r_V_11_fu_431_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_2_fu_414_p1),to_integer(unsigned('0' & zext_ln1340_3_fu_421_p1(31-1 downto 0)))));
    r_V_9_fu_370_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_353_p1),to_integer(unsigned('0' & zext_ln1340_fu_360_p1(31-1 downto 0)))));
    r_V_fu_364_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_353_p1),to_integer(unsigned('0' & zext_ln1340_fu_360_p1(31-1 downto 0)))));
    result_V_17_fu_466_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_700));
    result_V_20_fu_477_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_3_reg_706));
    result_V_21_fu_482_p3 <= 
        result_V_20_fu_477_p2 when (p_Result_3_reg_680_pp0_iter19_reg(0) = '1') else 
        val_3_reg_706;
    result_V_fu_471_p3 <= 
        result_V_17_fu_466_p2 when (p_Result_s_reg_660_pp0_iter19_reg(0) = '1') else 
        val_reg_700;
        sext_ln1340_3_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_3_reg_695),32));

        sext_ln1340_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_675),32));

        sext_ln1364_2_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_2_fu_326_p2),9));

        sext_ln1364_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_265_p2),9));

        sext_ln34_6_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_V_21_reg_717),48));

        sext_ln34_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_V_reg_712),48));

    sub_ln1364_2_fu_326_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_42_fu_294_p4));
    sub_ln1364_fu_265_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_40_fu_233_p4));
    tmp_39_fu_437_p3 <= r_V_10_fu_425_p2(24 downto 24);
    tmp_40_fu_233_p4 <= data_V_fu_222_p1(30 downto 23);
    tmp_41_fu_243_p1 <= data_V_fu_222_p1(23 - 1 downto 0);
    tmp_42_fu_294_p4 <= data_V_3_fu_283_p1(30 downto 23);
    tmp_43_fu_304_p1 <= data_V_3_fu_283_p1(23 - 1 downto 0);
    tmp_6_fu_449_p4 <= r_V_11_fu_431_p2(55 downto 24);
    tmp_fu_376_p3 <= r_V_fu_364_p2(24 downto 24);
    tmp_s_fu_388_p4 <= r_V_9_fu_370_p2(55 downto 24);
    ush_3_fu_336_p3 <= 
        sext_ln1364_2_fu_332_p1 when (isNeg_3_fu_318_p3(0) = '1') else 
        add_ln344_2_fu_312_p2;
    ush_fu_275_p3 <= 
        sext_ln1364_fu_271_p1 when (isNeg_fu_257_p3(0) = '1') else 
        add_ln344_fu_251_p2;
    val_3_fu_459_p3 <= 
        zext_ln671_2_fu_445_p1 when (isNeg_3_reg_690(0) = '1') else 
        tmp_6_fu_449_p4;
    val_fu_398_p3 <= 
        zext_ln671_fu_384_p1 when (isNeg_reg_670(0) = '1') else 
        tmp_s_fu_388_p4;
    zext_ln1340_3_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_3_fu_418_p1),79));
    zext_ln1340_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_357_p1),79));
    zext_ln151_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_82),64));
    zext_ln15_2_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_2_fu_405_p4),79));
    zext_ln15_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_344_p4),79));
    zext_ln344_2_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_42_fu_294_p4),9));
    zext_ln344_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_40_fu_233_p4),9));
    zext_ln671_2_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_39_fu_437_p3),32));
    zext_ln671_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_376_p3),32));
end behav;
