// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_rrt_Pipeline_VITIS_LOOP_47_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        r,
        q_1_out,
        q_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] r;
output  [31:0] q_1_out;
output   q_1_out_ap_vld;

reg ap_idle;
reg q_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_83_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] r_2_fu_40;
wire   [31:0] r_4_fu_159_p3;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [30:0] b_1_fu_44;
wire   [30:0] zext_ln56_fu_177_p1;
reg   [31:0] q_1_fu_48;
wire   [31:0] q_3_fu_143_p3;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] b_i_cast_fu_95_p1;
wire   [30:0] trunc_ln49_fu_103_p1;
wire   [31:0] t_fu_107_p2;
wire   [0:0] icmp_ln50_fu_119_p2;
wire   [30:0] empty_39_fu_99_p1;
wire   [30:0] add_ln43_fu_113_p2;
wire   [0:0] xor_ln50_fu_125_p2;
wire   [31:0] q_fu_137_p2;
wire   [30:0] r_3_fu_131_p2;
wire   [30:0] select_ln50_fu_151_p3;
wire   [29:0] b_3_fu_167_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

rrt_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_1_fu_44 <= 31'd1073741824;
        end else if (((icmp_ln47_fu_83_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            b_1_fu_44 <= zext_ln56_fu_177_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            q_1_fu_48 <= 32'd0;
        end else if (((icmp_ln47_fu_83_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            q_1_fu_48 <= q_3_fu_143_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_2_fu_40 <= r;
        end else if (((icmp_ln47_fu_83_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            r_2_fu_40 <= r_4_fu_159_p3;
        end
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_83_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_83_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        q_1_out_ap_vld = 1'b1;
    end else begin
        q_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_113_p2 = (b_1_fu_44 + trunc_ln49_fu_103_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign b_3_fu_167_p4 = {{b_1_fu_44[30:1]}};

assign b_i_cast_fu_95_p1 = b_1_fu_44;

assign empty_39_fu_99_p1 = r_2_fu_40[30:0];

assign icmp_ln47_fu_83_p2 = ((b_1_fu_44 > 31'd64) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_119_p2 = ((r_2_fu_40 < t_fu_107_p2) ? 1'b1 : 1'b0);

assign q_1_out = q_1_fu_48;

assign q_3_fu_143_p3 = ((xor_ln50_fu_125_p2[0:0] == 1'b1) ? q_fu_137_p2 : q_1_fu_48);

assign q_fu_137_p2 = (t_fu_107_p2 + b_i_cast_fu_95_p1);

assign r_3_fu_131_p2 = (empty_39_fu_99_p1 - add_ln43_fu_113_p2);

assign r_4_fu_159_p3 = {{select_ln50_fu_151_p3}, {1'd0}};

assign select_ln50_fu_151_p3 = ((xor_ln50_fu_125_p2[0:0] == 1'b1) ? r_3_fu_131_p2 : empty_39_fu_99_p1);

assign t_fu_107_p2 = (b_i_cast_fu_95_p1 + q_1_fu_48);

assign trunc_ln49_fu_103_p1 = q_1_fu_48[30:0];

assign xor_ln50_fu_125_p2 = (icmp_ln50_fu_119_p2 ^ 1'd1);

assign zext_ln56_fu_177_p1 = b_3_fu_167_p4;

endmodule //rrt_rrt_Pipeline_VITIS_LOOP_47_1
