// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_rrt_Pipeline_VITIS_LOOP_271_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dataInStream_TVALID,
        N,
        dataInStream_TDATA,
        dataInStream_TREADY,
        dataInStream_TKEEP,
        dataInStream_TSTRB,
        dataInStream_TUSER,
        dataInStream_TLAST,
        dataInStream_TID,
        dataInStream_TDEST,
        RRT_Star_Position_x_address0,
        RRT_Star_Position_x_ce0,
        RRT_Star_Position_x_we0,
        RRT_Star_Position_x_d0,
        RRT_Star_Position_y_address0,
        RRT_Star_Position_y_ce0,
        RRT_Star_Position_y_we0,
        RRT_Star_Position_y_d0,
        RRT_Star_Location_List_address0,
        RRT_Star_Location_List_ce0,
        RRT_Star_Location_List_we0,
        RRT_Star_Location_List_d0,
        conv_i_i,
        conv9_i_i,
        Pos_Nearest_Node_out,
        Pos_Nearest_Node_out_ap_vld,
        output_stream_keep_V_out,
        output_stream_keep_V_out_ap_vld,
        output_stream_strb_V_out,
        output_stream_strb_V_out_ap_vld,
        tmp_user_V_out,
        tmp_user_V_out_ap_vld,
        tmp_id_V_out,
        tmp_id_V_out_ap_vld,
        tmp_dest_V_out,
        tmp_dest_V_out_ap_vld,
        grp_FloatToFixed_16ul_s_fu_364_p_din1,
        grp_FloatToFixed_16ul_s_fu_364_p_dout0,
        grp_FloatToFixed_16ul_s_fu_364_p_ce,
        grp_FloatToFixed_16ul_s_fu_370_p_din1,
        grp_FloatToFixed_16ul_s_fu_370_p_dout0,
        grp_FloatToFixed_16ul_s_fu_370_p_ce,
        grp_fu_515_p_din0,
        grp_fu_515_p_din1,
        grp_fu_515_p_opcode,
        grp_fu_515_p_dout0,
        grp_fu_515_p_ce,
        grp_fu_519_p_din0,
        grp_fu_519_p_din1,
        grp_fu_519_p_opcode,
        grp_fu_519_p_dout0,
        grp_fu_519_p_ce,
        grp_fu_531_p_din0,
        grp_fu_531_p_dout0,
        grp_fu_531_p_ce,
        grp_fu_1694_p_din0,
        grp_fu_1694_p_dout0,
        grp_fu_1694_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   dataInStream_TVALID;
input  [31:0] N;
input  [63:0] dataInStream_TDATA;
output   dataInStream_TREADY;
input  [7:0] dataInStream_TKEEP;
input  [7:0] dataInStream_TSTRB;
input  [1:0] dataInStream_TUSER;
input  [0:0] dataInStream_TLAST;
input  [4:0] dataInStream_TID;
input  [5:0] dataInStream_TDEST;
output  [13:0] RRT_Star_Position_x_address0;
output   RRT_Star_Position_x_ce0;
output   RRT_Star_Position_x_we0;
output  [31:0] RRT_Star_Position_x_d0;
output  [13:0] RRT_Star_Position_y_address0;
output   RRT_Star_Position_y_ce0;
output   RRT_Star_Position_y_we0;
output  [31:0] RRT_Star_Position_y_d0;
output  [13:0] RRT_Star_Location_List_address0;
output   RRT_Star_Location_List_ce0;
output   RRT_Star_Location_List_we0;
output  [15:0] RRT_Star_Location_List_d0;
input  [31:0] conv_i_i;
input  [31:0] conv9_i_i;
output  [31:0] Pos_Nearest_Node_out;
output   Pos_Nearest_Node_out_ap_vld;
output  [3:0] output_stream_keep_V_out;
output   output_stream_keep_V_out_ap_vld;
output  [3:0] output_stream_strb_V_out;
output   output_stream_strb_V_out_ap_vld;
output  [1:0] tmp_user_V_out;
output   tmp_user_V_out_ap_vld;
output  [4:0] tmp_id_V_out;
output   tmp_id_V_out_ap_vld;
output  [5:0] tmp_dest_V_out;
output   tmp_dest_V_out_ap_vld;
output  [31:0] grp_FloatToFixed_16ul_s_fu_364_p_din1;
input  [31:0] grp_FloatToFixed_16ul_s_fu_364_p_dout0;
output   grp_FloatToFixed_16ul_s_fu_364_p_ce;
output  [31:0] grp_FloatToFixed_16ul_s_fu_370_p_din1;
input  [31:0] grp_FloatToFixed_16ul_s_fu_370_p_dout0;
output   grp_FloatToFixed_16ul_s_fu_370_p_ce;
output  [31:0] grp_fu_515_p_din0;
output  [31:0] grp_fu_515_p_din1;
output  [0:0] grp_fu_515_p_opcode;
input  [31:0] grp_fu_515_p_dout0;
output   grp_fu_515_p_ce;
output  [31:0] grp_fu_519_p_din0;
output  [31:0] grp_fu_519_p_din1;
output  [0:0] grp_fu_519_p_opcode;
input  [31:0] grp_fu_519_p_dout0;
output   grp_fu_519_p_ce;
output  [31:0] grp_fu_531_p_din0;
input  [31:0] grp_fu_531_p_dout0;
output   grp_fu_531_p_ce;
output  [31:0] grp_fu_1694_p_din0;
input  [31:0] grp_fu_1694_p_dout0;
output   grp_fu_1694_p_ce;

reg ap_idle;
reg dataInStream_TREADY;
reg RRT_Star_Position_x_ce0;
reg RRT_Star_Position_x_we0;
reg RRT_Star_Position_y_ce0;
reg RRT_Star_Position_y_we0;
reg RRT_Star_Location_List_ce0;
reg RRT_Star_Location_List_we0;
reg Pos_Nearest_Node_out_ap_vld;
reg output_stream_keep_V_out_ap_vld;
reg output_stream_strb_V_out_ap_vld;
reg tmp_user_V_out_ap_vld;
reg tmp_id_V_out_ap_vld;
reg tmp_dest_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln271_fu_327_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    dataInStream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln271_1_fu_323_p1;
reg   [31:0] zext_ln271_1_reg_904;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter1_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter2_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter3_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter4_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter5_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter6_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter7_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter8_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter9_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter10_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter11_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter12_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter13_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter14_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter15_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter16_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter17_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter18_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter19_reg;
reg   [31:0] zext_ln271_1_reg_904_pp0_iter20_reg;
reg   [0:0] icmp_ln271_reg_909;
reg   [0:0] icmp_ln271_reg_909_pp0_iter1_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter2_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter3_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter4_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter5_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter6_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter7_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter8_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter9_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter10_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter11_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter12_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter13_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter14_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter15_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter16_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter17_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter18_reg;
reg   [0:0] icmp_ln271_reg_909_pp0_iter19_reg;
wire   [63:0] zext_ln271_fu_339_p1;
reg   [63:0] zext_ln271_reg_913;
reg   [63:0] zext_ln271_reg_913_pp0_iter1_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter2_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter3_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter4_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter5_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter6_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter7_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter8_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter9_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter10_reg;
reg   [63:0] zext_ln271_reg_913_pp0_iter11_reg;
wire   [0:0] icmp_ln284_fu_403_p2;
reg   [0:0] icmp_ln284_reg_929;
reg   [0:0] icmp_ln284_reg_929_pp0_iter1_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter2_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter3_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter4_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter5_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter6_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter7_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter8_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter9_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter10_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter11_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter12_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter13_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter14_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter15_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter16_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter17_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter18_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter19_reg;
reg   [0:0] icmp_ln284_reg_929_pp0_iter20_reg;
wire   [31:0] grp_fu_297_p1;
wire   [31:0] grp_fu_301_p1;
reg   [31:0] B_x_reg_945;
reg   [31:0] B_y_reg_951;
reg   [31:0] conv_i_i_i_reg_957;
reg   [31:0] conv_i2_i_i_reg_962;
reg   [31:0] dc_reg_967;
reg   [31:0] dc_1_reg_972;
wire   [31:0] result_V_fu_578_p3;
reg   [31:0] result_V_reg_977;
wire   [31:0] result_V_6_fu_717_p3;
reg   [31:0] result_V_6_reg_982;
reg   [31:0] trunc_ln34_2_reg_987;
reg   [31:0] trunc_ln34_3_reg_992;
reg    grp_FloatToFixed_16ul_s_fu_273_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call15;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call15;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call15;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call15;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call15;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call15;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call15;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call15;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call15;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call15;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call15;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call15;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call15;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call15;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call15;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call15;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call15;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call15;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call15;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call15;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call15;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call15;
reg    ap_block_pp0_stage0_11001_ignoreCallOp73;
reg    grp_FloatToFixed_16ul_s_fu_278_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call21;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call21;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call21;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call21;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call21;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call21;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call21;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call21;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call21;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call21;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call21;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call21;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call21;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call21;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call21;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call21;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call21;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call21;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call21;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call21;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call21;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call21;
reg    ap_block_pp0_stage0_11001_ignoreCallOp75;
reg   [5:0] input_stream_dest_V_fu_124;
reg   [4:0] input_stream_id_V_fu_128;
reg   [1:0] input_stream_user_V_fu_132;
reg   [3:0] output_stream_strb_V_fu_136;
wire   [3:0] empty_41_fu_413_p1;
reg   [3:0] output_stream_keep_V_fu_140;
wire   [3:0] empty_40_fu_409_p1;
reg   [31:0] Pos_Nearest_Node_fu_144;
wire   [31:0] Pos_Nearest_Node_2_fu_794_p3;
wire    ap_loop_init;
reg   [31:0] Dist_fu_148;
wire   [31:0] Dist_2_fu_801_p3;
reg   [13:0] i_fu_152;
wire   [13:0] add_ln271_fu_333_p2;
reg   [13:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] grp_fu_297_p0;
wire   [15:0] grp_fu_301_p0;
wire   [15:0] trunc_ln277_fu_368_p1;
wire   [15:0] trunc_ln3_fu_377_p4;
wire   [31:0] data_V_fu_447_p1;
wire   [22:0] tmp_7_fu_468_p1;
wire   [24:0] mantissa_fu_472_p4;
wire   [7:0] tmp_6_fu_458_p4;
wire   [8:0] zext_ln344_fu_486_p1;
wire   [8:0] add_ln344_fu_490_p2;
wire   [7:0] sub_ln1364_fu_504_p2;
wire   [0:0] isNeg_fu_496_p3;
wire  signed [8:0] sext_ln1364_fu_510_p1;
wire   [8:0] ush_fu_514_p3;
wire  signed [31:0] sext_ln1340_fu_522_p1;
wire   [78:0] zext_ln15_fu_482_p1;
wire   [78:0] zext_ln1340_fu_526_p1;
wire   [78:0] r_V_fu_530_p2;
wire   [0:0] tmp_fu_542_p3;
wire   [78:0] r_V_1_fu_536_p2;
wire   [31:0] zext_ln671_fu_550_p1;
wire   [31:0] tmp_s_fu_554_p4;
wire   [31:0] val_fu_564_p3;
wire   [0:0] p_Result_s_fu_450_p3;
wire   [31:0] result_V_1_fu_572_p2;
wire   [31:0] data_V_1_fu_586_p1;
wire   [22:0] tmp_9_fu_607_p1;
wire   [24:0] mantissa_1_fu_611_p4;
wire   [7:0] tmp_8_fu_597_p4;
wire   [8:0] zext_ln344_1_fu_625_p1;
wire   [8:0] add_ln344_1_fu_629_p2;
wire   [7:0] sub_ln1364_1_fu_643_p2;
wire   [0:0] isNeg_1_fu_635_p3;
wire  signed [8:0] sext_ln1364_1_fu_649_p1;
wire   [8:0] ush_1_fu_653_p3;
wire  signed [31:0] sext_ln1340_1_fu_661_p1;
wire   [78:0] zext_ln15_1_fu_621_p1;
wire   [78:0] zext_ln1340_1_fu_665_p1;
wire   [78:0] r_V_2_fu_669_p2;
wire   [0:0] tmp_5_fu_681_p3;
wire   [78:0] r_V_3_fu_675_p2;
wire   [31:0] zext_ln671_1_fu_689_p1;
wire   [31:0] tmp_2_fu_693_p4;
wire   [31:0] val_1_fu_703_p3;
wire   [0:0] p_Result_1_fu_589_p3;
wire   [31:0] result_V_4_fu_711_p2;
wire  signed [31:0] mul_ln34_fu_728_p0;
wire  signed [47:0] sext_ln34_fu_725_p1;
wire  signed [31:0] mul_ln34_fu_728_p1;
wire   [47:0] mul_ln34_fu_728_p2;
wire  signed [31:0] mul_ln34_1_fu_747_p0;
wire  signed [47:0] sext_ln34_1_fu_744_p1;
wire  signed [31:0] mul_ln34_1_fu_747_p1;
wire   [47:0] mul_ln34_1_fu_747_p2;
wire   [31:0] D_fu_769_p2;
wire   [0:0] icmp_ln290_fu_773_p2;
wire   [31:0] Pos_Nearest_Node_1_fu_779_p3;
wire   [31:0] Dist_1_fu_786_p3;
reg    ap_block_pp0_stage0_00001;
reg    grp_fu_283_ce;
reg    grp_fu_287_ce;
reg    grp_fu_291_ce;
reg    grp_fu_294_ce;
reg    grp_fu_297_ce;
reg    grp_fu_301_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_done_reg = 1'b0;
end

rrt_hptosp_16ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_2_no_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_297_p0),
    .ce(grp_fu_297_ce),
    .dout(grp_fu_297_p1)
);

rrt_hptosp_16ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
hptosp_16ns_32_2_no_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_301_p0),
    .ce(grp_fu_301_ce),
    .dout(grp_fu_301_p1)
);

rrt_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U37(
    .din0(mul_ln34_fu_728_p0),
    .din1(mul_ln34_fu_728_p1),
    .dout(mul_ln34_fu_728_p2)
);

rrt_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U38(
    .din0(mul_ln34_1_fu_747_p0),
    .din1(mul_ln34_1_fu_747_p1),
    .dout(mul_ln34_1_fu_747_p2)
);

rrt_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Dist_fu_148 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter21 == 1'b1)) begin
            Dist_fu_148 <= Dist_2_fu_801_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Pos_Nearest_Node_fu_144 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter21 == 1'b1)) begin
            Pos_Nearest_Node_fu_144 <= Pos_Nearest_Node_2_fu_794_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln271_fu_327_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            i_fu_152 <= add_ln271_fu_333_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_152 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        B_x_reg_945 <= grp_FloatToFixed_16ul_s_fu_364_p_dout0;
        B_y_reg_951 <= grp_FloatToFixed_16ul_s_fu_370_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv_i2_i_i_reg_962 <= grp_fu_1694_p_dout0;
        conv_i_i_i_reg_957 <= grp_fu_531_p_dout0;
        dc_1_reg_972 <= grp_fu_519_p_dout0;
        dc_reg_967 <= grp_fu_515_p_dout0;
        icmp_ln271_reg_909_pp0_iter10_reg <= icmp_ln271_reg_909_pp0_iter9_reg;
        icmp_ln271_reg_909_pp0_iter11_reg <= icmp_ln271_reg_909_pp0_iter10_reg;
        icmp_ln271_reg_909_pp0_iter12_reg <= icmp_ln271_reg_909_pp0_iter11_reg;
        icmp_ln271_reg_909_pp0_iter13_reg <= icmp_ln271_reg_909_pp0_iter12_reg;
        icmp_ln271_reg_909_pp0_iter14_reg <= icmp_ln271_reg_909_pp0_iter13_reg;
        icmp_ln271_reg_909_pp0_iter15_reg <= icmp_ln271_reg_909_pp0_iter14_reg;
        icmp_ln271_reg_909_pp0_iter16_reg <= icmp_ln271_reg_909_pp0_iter15_reg;
        icmp_ln271_reg_909_pp0_iter17_reg <= icmp_ln271_reg_909_pp0_iter16_reg;
        icmp_ln271_reg_909_pp0_iter18_reg <= icmp_ln271_reg_909_pp0_iter17_reg;
        icmp_ln271_reg_909_pp0_iter19_reg <= icmp_ln271_reg_909_pp0_iter18_reg;
        icmp_ln271_reg_909_pp0_iter2_reg <= icmp_ln271_reg_909_pp0_iter1_reg;
        icmp_ln271_reg_909_pp0_iter3_reg <= icmp_ln271_reg_909_pp0_iter2_reg;
        icmp_ln271_reg_909_pp0_iter4_reg <= icmp_ln271_reg_909_pp0_iter3_reg;
        icmp_ln271_reg_909_pp0_iter5_reg <= icmp_ln271_reg_909_pp0_iter4_reg;
        icmp_ln271_reg_909_pp0_iter6_reg <= icmp_ln271_reg_909_pp0_iter5_reg;
        icmp_ln271_reg_909_pp0_iter7_reg <= icmp_ln271_reg_909_pp0_iter6_reg;
        icmp_ln271_reg_909_pp0_iter8_reg <= icmp_ln271_reg_909_pp0_iter7_reg;
        icmp_ln271_reg_909_pp0_iter9_reg <= icmp_ln271_reg_909_pp0_iter8_reg;
        icmp_ln284_reg_929_pp0_iter10_reg <= icmp_ln284_reg_929_pp0_iter9_reg;
        icmp_ln284_reg_929_pp0_iter11_reg <= icmp_ln284_reg_929_pp0_iter10_reg;
        icmp_ln284_reg_929_pp0_iter12_reg <= icmp_ln284_reg_929_pp0_iter11_reg;
        icmp_ln284_reg_929_pp0_iter13_reg <= icmp_ln284_reg_929_pp0_iter12_reg;
        icmp_ln284_reg_929_pp0_iter14_reg <= icmp_ln284_reg_929_pp0_iter13_reg;
        icmp_ln284_reg_929_pp0_iter15_reg <= icmp_ln284_reg_929_pp0_iter14_reg;
        icmp_ln284_reg_929_pp0_iter16_reg <= icmp_ln284_reg_929_pp0_iter15_reg;
        icmp_ln284_reg_929_pp0_iter17_reg <= icmp_ln284_reg_929_pp0_iter16_reg;
        icmp_ln284_reg_929_pp0_iter18_reg <= icmp_ln284_reg_929_pp0_iter17_reg;
        icmp_ln284_reg_929_pp0_iter19_reg <= icmp_ln284_reg_929_pp0_iter18_reg;
        icmp_ln284_reg_929_pp0_iter20_reg <= icmp_ln284_reg_929_pp0_iter19_reg;
        icmp_ln284_reg_929_pp0_iter2_reg <= icmp_ln284_reg_929_pp0_iter1_reg;
        icmp_ln284_reg_929_pp0_iter3_reg <= icmp_ln284_reg_929_pp0_iter2_reg;
        icmp_ln284_reg_929_pp0_iter4_reg <= icmp_ln284_reg_929_pp0_iter3_reg;
        icmp_ln284_reg_929_pp0_iter5_reg <= icmp_ln284_reg_929_pp0_iter4_reg;
        icmp_ln284_reg_929_pp0_iter6_reg <= icmp_ln284_reg_929_pp0_iter5_reg;
        icmp_ln284_reg_929_pp0_iter7_reg <= icmp_ln284_reg_929_pp0_iter6_reg;
        icmp_ln284_reg_929_pp0_iter8_reg <= icmp_ln284_reg_929_pp0_iter7_reg;
        icmp_ln284_reg_929_pp0_iter9_reg <= icmp_ln284_reg_929_pp0_iter8_reg;
        result_V_6_reg_982 <= result_V_6_fu_717_p3;
        result_V_reg_977 <= result_V_fu_578_p3;
        trunc_ln34_2_reg_987 <= {{mul_ln34_fu_728_p2[47:16]}};
        trunc_ln34_3_reg_992 <= {{mul_ln34_1_fu_747_p2[47:16]}};
        zext_ln271_1_reg_904_pp0_iter10_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter9_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter11_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter10_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter12_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter11_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter13_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter12_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter14_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter13_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter15_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter14_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter16_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter15_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter17_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter16_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter18_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter17_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter19_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter18_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter20_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter19_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter2_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter1_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter3_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter2_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter4_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter3_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter5_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter4_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter6_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter5_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter7_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter6_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter8_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter7_reg[13 : 0];
        zext_ln271_1_reg_904_pp0_iter9_reg[13 : 0] <= zext_ln271_1_reg_904_pp0_iter8_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter10_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter9_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter11_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter10_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter2_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter1_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter3_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter2_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter4_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter3_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter5_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter4_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter6_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter5_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter7_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter6_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter8_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter7_reg[13 : 0];
        zext_ln271_reg_913_pp0_iter9_reg[13 : 0] <= zext_ln271_reg_913_pp0_iter8_reg[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln271_reg_909 <= icmp_ln271_fu_327_p2;
        icmp_ln271_reg_909_pp0_iter1_reg <= icmp_ln271_reg_909;
        icmp_ln284_reg_929_pp0_iter1_reg <= icmp_ln284_reg_929;
        zext_ln271_1_reg_904[13 : 0] <= zext_ln271_1_fu_323_p1[13 : 0];
        zext_ln271_1_reg_904_pp0_iter1_reg[13 : 0] <= zext_ln271_1_reg_904[13 : 0];
        zext_ln271_reg_913_pp0_iter1_reg[13 : 0] <= zext_ln271_reg_913[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln284_reg_929 <= icmp_ln284_fu_403_p2;
        zext_ln271_reg_913[13 : 0] <= zext_ln271_fu_339_p1[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln271_fu_327_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_stream_dest_V_fu_124 <= dataInStream_TDEST;
        input_stream_id_V_fu_128 <= dataInStream_TID;
        input_stream_user_V_fu_132 <= dataInStream_TUSER;
        output_stream_keep_V_fu_140 <= empty_40_fu_409_p1;
        output_stream_strb_V_fu_136 <= empty_41_fu_413_p1;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Pos_Nearest_Node_out_ap_vld = 1'b1;
    end else begin
        Pos_Nearest_Node_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Location_List_ce0 = 1'b1;
    end else begin
        RRT_Star_Location_List_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_fu_327_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Location_List_we0 = 1'b1;
    end else begin
        RRT_Star_Location_List_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Position_x_ce0 = 1'b1;
    end else begin
        RRT_Star_Position_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Position_x_we0 = 1'b1;
    end else begin
        RRT_Star_Position_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Position_y_ce0 = 1'b1;
    end else begin
        RRT_Star_Position_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Position_y_we0 = 1'b1;
    end else begin
        RRT_Star_Position_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_fu_327_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_152;
    end
end

always @ (*) begin
    if (((icmp_ln271_fu_327_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        dataInStream_TDATA_blk_n = dataInStream_TVALID;
    end else begin
        dataInStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln271_fu_327_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dataInStream_TREADY = 1'b1;
    end else begin
        dataInStream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp73))) begin
        grp_FloatToFixed_16ul_s_fu_273_ap_ce = 1'b1;
    end else begin
        grp_FloatToFixed_16ul_s_fu_273_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp75))) begin
        grp_FloatToFixed_16ul_s_fu_278_ap_ce = 1'b1;
    end else begin
        grp_FloatToFixed_16ul_s_fu_278_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_283_ce = 1'b1;
    end else begin
        grp_fu_283_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_287_ce = 1'b1;
    end else begin
        grp_fu_287_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_291_ce = 1'b1;
    end else begin
        grp_fu_291_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_294_ce = 1'b1;
    end else begin
        grp_fu_294_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_297_ce = 1'b1;
    end else begin
        grp_fu_297_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_301_ce = 1'b1;
    end else begin
        grp_fu_301_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_stream_keep_V_out_ap_vld = 1'b1;
    end else begin
        output_stream_keep_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_stream_strb_V_out_ap_vld = 1'b1;
    end else begin
        output_stream_strb_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_dest_V_out_ap_vld = 1'b1;
    end else begin
        tmp_dest_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_id_V_out_ap_vld = 1'b1;
    end else begin
        tmp_id_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_909_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_user_V_out_ap_vld = 1'b1;
    end else begin
        tmp_user_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D_fu_769_p2 = (trunc_ln34_3_reg_992 + trunc_ln34_2_reg_987);

assign Dist_1_fu_786_p3 = ((icmp_ln290_fu_773_p2[0:0] == 1'b1) ? D_fu_769_p2 : Dist_fu_148);

assign Dist_2_fu_801_p3 = ((icmp_ln284_reg_929_pp0_iter20_reg[0:0] == 1'b1) ? D_fu_769_p2 : Dist_1_fu_786_p3);

assign Pos_Nearest_Node_1_fu_779_p3 = ((icmp_ln290_fu_773_p2[0:0] == 1'b1) ? zext_ln271_1_reg_904_pp0_iter20_reg : Pos_Nearest_Node_fu_144);

assign Pos_Nearest_Node_2_fu_794_p3 = ((icmp_ln284_reg_929_pp0_iter20_reg[0:0] == 1'b1) ? 32'd0 : Pos_Nearest_Node_1_fu_779_p3);

assign Pos_Nearest_Node_out = Pos_Nearest_Node_fu_144;

assign RRT_Star_Location_List_address0 = zext_ln271_fu_339_p1;

assign RRT_Star_Location_List_d0 = {{dataInStream_TDATA[47:32]}};

assign RRT_Star_Position_x_address0 = zext_ln271_reg_913_pp0_iter11_reg;

assign RRT_Star_Position_x_d0 = B_x_reg_945;

assign RRT_Star_Position_y_address0 = zext_ln271_reg_913_pp0_iter11_reg;

assign RRT_Star_Position_y_d0 = B_y_reg_951;

assign add_ln271_fu_333_p2 = (ap_sig_allocacmp_i_1 + 14'd1);

assign add_ln344_1_fu_629_p2 = ($signed(zext_ln344_1_fu_625_p1) + $signed(9'd385));

assign add_ln344_fu_490_p2 = ($signed(zext_ln344_fu_486_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp73 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp75 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call21 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call15 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call21 = ((icmp_ln271_fu_327_p2 == 1'd0) & (dataInStream_TVALID == 1'b0));
end

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call15 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign data_V_1_fu_586_p1 = dc_1_reg_972;

assign data_V_fu_447_p1 = dc_reg_967;

assign empty_40_fu_409_p1 = dataInStream_TKEEP[3:0];

assign empty_41_fu_413_p1 = dataInStream_TSTRB[3:0];

assign grp_FloatToFixed_16ul_s_fu_364_p_ce = grp_FloatToFixed_16ul_s_fu_273_ap_ce;

assign grp_FloatToFixed_16ul_s_fu_364_p_din1 = grp_fu_297_p1;

assign grp_FloatToFixed_16ul_s_fu_370_p_ce = grp_FloatToFixed_16ul_s_fu_278_ap_ce;

assign grp_FloatToFixed_16ul_s_fu_370_p_din1 = grp_fu_301_p1;

assign grp_fu_1694_p_ce = grp_fu_294_ce;

assign grp_fu_1694_p_din0 = B_y_reg_951;

assign grp_fu_297_p0 = trunc_ln277_fu_368_p1;

assign grp_fu_301_p0 = trunc_ln3_fu_377_p4;

assign grp_fu_515_p_ce = grp_fu_283_ce;

assign grp_fu_515_p_din0 = conv_i_i;

assign grp_fu_515_p_din1 = conv_i_i_i_reg_957;

assign grp_fu_515_p_opcode = 2'd1;

assign grp_fu_519_p_ce = grp_fu_287_ce;

assign grp_fu_519_p_din0 = conv9_i_i;

assign grp_fu_519_p_din1 = conv_i2_i_i_reg_962;

assign grp_fu_519_p_opcode = 2'd1;

assign grp_fu_531_p_ce = grp_fu_291_ce;

assign grp_fu_531_p_din0 = B_x_reg_945;

assign icmp_ln271_fu_327_p2 = ((zext_ln271_1_fu_323_p1 == N) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_403_p2 = ((ap_sig_allocacmp_i_1 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_773_p2 = (($signed(D_fu_769_p2) < $signed(Dist_fu_148)) ? 1'b1 : 1'b0);

assign isNeg_1_fu_635_p3 = add_ln344_1_fu_629_p2[32'd8];

assign isNeg_fu_496_p3 = add_ln344_fu_490_p2[32'd8];

assign mantissa_1_fu_611_p4 = {{{{1'd1}, {tmp_9_fu_607_p1}}}, {1'd0}};

assign mantissa_fu_472_p4 = {{{{1'd1}, {tmp_7_fu_468_p1}}}, {1'd0}};

assign mul_ln34_1_fu_747_p0 = sext_ln34_1_fu_744_p1;

assign mul_ln34_1_fu_747_p1 = sext_ln34_1_fu_744_p1;

assign mul_ln34_fu_728_p0 = sext_ln34_fu_725_p1;

assign mul_ln34_fu_728_p1 = sext_ln34_fu_725_p1;

assign output_stream_keep_V_out = output_stream_keep_V_fu_140;

assign output_stream_strb_V_out = output_stream_strb_V_fu_136;

assign p_Result_1_fu_589_p3 = data_V_1_fu_586_p1[32'd31];

assign p_Result_s_fu_450_p3 = data_V_fu_447_p1[32'd31];

assign r_V_1_fu_536_p2 = zext_ln15_fu_482_p1 << zext_ln1340_fu_526_p1;

assign r_V_2_fu_669_p2 = zext_ln15_1_fu_621_p1 >> zext_ln1340_1_fu_665_p1;

assign r_V_3_fu_675_p2 = zext_ln15_1_fu_621_p1 << zext_ln1340_1_fu_665_p1;

assign r_V_fu_530_p2 = zext_ln15_fu_482_p1 >> zext_ln1340_fu_526_p1;

assign result_V_1_fu_572_p2 = (32'd0 - val_fu_564_p3);

assign result_V_4_fu_711_p2 = (32'd0 - val_1_fu_703_p3);

assign result_V_6_fu_717_p3 = ((p_Result_1_fu_589_p3[0:0] == 1'b1) ? result_V_4_fu_711_p2 : val_1_fu_703_p3);

assign result_V_fu_578_p3 = ((p_Result_s_fu_450_p3[0:0] == 1'b1) ? result_V_1_fu_572_p2 : val_fu_564_p3);

assign sext_ln1340_1_fu_661_p1 = $signed(ush_1_fu_653_p3);

assign sext_ln1340_fu_522_p1 = $signed(ush_fu_514_p3);

assign sext_ln1364_1_fu_649_p1 = $signed(sub_ln1364_1_fu_643_p2);

assign sext_ln1364_fu_510_p1 = $signed(sub_ln1364_fu_504_p2);

assign sext_ln34_1_fu_744_p1 = $signed(result_V_6_reg_982);

assign sext_ln34_fu_725_p1 = $signed(result_V_reg_977);

assign sub_ln1364_1_fu_643_p2 = (8'd127 - tmp_8_fu_597_p4);

assign sub_ln1364_fu_504_p2 = (8'd127 - tmp_6_fu_458_p4);

assign tmp_2_fu_693_p4 = {{r_V_3_fu_675_p2[55:24]}};

assign tmp_5_fu_681_p3 = r_V_2_fu_669_p2[32'd24];

assign tmp_6_fu_458_p4 = {{data_V_fu_447_p1[30:23]}};

assign tmp_7_fu_468_p1 = data_V_fu_447_p1[22:0];

assign tmp_8_fu_597_p4 = {{data_V_1_fu_586_p1[30:23]}};

assign tmp_9_fu_607_p1 = data_V_1_fu_586_p1[22:0];

assign tmp_dest_V_out = input_stream_dest_V_fu_124;

assign tmp_fu_542_p3 = r_V_fu_530_p2[32'd24];

assign tmp_id_V_out = input_stream_id_V_fu_128;

assign tmp_s_fu_554_p4 = {{r_V_1_fu_536_p2[55:24]}};

assign tmp_user_V_out = input_stream_user_V_fu_132;

assign trunc_ln277_fu_368_p1 = dataInStream_TDATA[15:0];

assign trunc_ln3_fu_377_p4 = {{dataInStream_TDATA[31:16]}};

assign ush_1_fu_653_p3 = ((isNeg_1_fu_635_p3[0:0] == 1'b1) ? sext_ln1364_1_fu_649_p1 : add_ln344_1_fu_629_p2);

assign ush_fu_514_p3 = ((isNeg_fu_496_p3[0:0] == 1'b1) ? sext_ln1364_fu_510_p1 : add_ln344_fu_490_p2);

assign val_1_fu_703_p3 = ((isNeg_1_fu_635_p3[0:0] == 1'b1) ? zext_ln671_1_fu_689_p1 : tmp_2_fu_693_p4);

assign val_fu_564_p3 = ((isNeg_fu_496_p3[0:0] == 1'b1) ? zext_ln671_fu_550_p1 : tmp_s_fu_554_p4);

assign zext_ln1340_1_fu_665_p1 = $unsigned(sext_ln1340_1_fu_661_p1);

assign zext_ln1340_fu_526_p1 = $unsigned(sext_ln1340_fu_522_p1);

assign zext_ln15_1_fu_621_p1 = mantissa_1_fu_611_p4;

assign zext_ln15_fu_482_p1 = mantissa_fu_472_p4;

assign zext_ln271_1_fu_323_p1 = ap_sig_allocacmp_i_1;

assign zext_ln271_fu_339_p1 = ap_sig_allocacmp_i_1;

assign zext_ln344_1_fu_625_p1 = tmp_8_fu_597_p4;

assign zext_ln344_fu_486_p1 = tmp_6_fu_458_p4;

assign zext_ln671_1_fu_689_p1 = tmp_5_fu_681_p3;

assign zext_ln671_fu_550_p1 = tmp_fu_542_p3;

always @ (posedge ap_clk) begin
    zext_ln271_1_reg_904[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter1_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter2_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter3_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter4_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter5_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter6_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter7_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter8_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter9_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter10_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter11_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter12_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter13_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter14_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter15_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter16_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter17_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter18_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter19_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_1_reg_904_pp0_iter20_reg[31:14] <= 18'b000000000000000000;
    zext_ln271_reg_913[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter4_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter5_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter6_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter7_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter8_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter9_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter10_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln271_reg_913_pp0_iter11_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //rrt_rrt_Pipeline_VITIS_LOOP_271_2
