// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_FloatToFixed_16ul_s (
        ap_clk,
        ap_rst,
        d,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] d;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln7_fu_101_p2;
reg   [0:0] icmp_ln7_reg_276;
reg   [0:0] icmp_ln7_reg_276_pp0_iter1_reg;
reg   [0:0] icmp_ln7_reg_276_pp0_iter2_reg;
reg   [0:0] icmp_ln7_reg_276_pp0_iter3_reg;
wire   [0:0] icmp_ln7_2_fu_107_p2;
reg   [0:0] icmp_ln7_2_reg_281;
reg   [0:0] icmp_ln7_2_reg_281_pp0_iter1_reg;
reg   [0:0] icmp_ln7_2_reg_281_pp0_iter2_reg;
reg   [0:0] icmp_ln7_2_reg_281_pp0_iter3_reg;
wire   [0:0] grp_fu_72_p2;
reg   [0:0] tmp_5_reg_286;
reg   [0:0] tmp_5_reg_286_pp0_iter2_reg;
reg   [0:0] tmp_5_reg_286_pp0_iter3_reg;
wire   [31:0] grp_fu_62_p2;
wire   [63:0] grp_fu_68_p1;
wire   [63:0] grp_fu_78_p2;
reg   [63:0] dc_reg_306;
wire    ap_block_pp0_stage0;
wire   [63:0] grp_fu_78_p1;
wire   [31:0] bitcast_ln7_fu_83_p1;
wire   [7:0] tmp_s_fu_87_p4;
wire   [22:0] trunc_ln7_fu_97_p1;
wire   [0:0] or_ln7_fu_113_p2;
wire   [0:0] and_ln7_fu_117_p2;
wire   [63:0] data_V_fu_131_p1;
wire   [51:0] tmp_56_fu_152_p1;
wire   [53:0] mantissa_fu_156_p4;
wire   [10:0] tmp_55_fu_142_p4;
wire   [11:0] zext_ln513_fu_170_p1;
wire   [11:0] add_ln513_fu_174_p2;
wire   [10:0] sub_ln1364_fu_188_p2;
wire   [0:0] isNeg_fu_180_p3;
wire  signed [11:0] sext_ln1364_fu_194_p1;
wire   [11:0] ush_fu_198_p3;
wire  signed [31:0] sext_ln1340_fu_206_p1;
wire   [136:0] zext_ln15_fu_166_p1;
wire   [136:0] zext_ln1340_fu_210_p1;
wire   [136:0] r_V_fu_214_p2;
wire   [0:0] tmp_fu_226_p3;
wire   [136:0] r_V_15_fu_220_p2;
wire   [31:0] zext_ln671_fu_234_p1;
wire   [31:0] tmp_10_fu_238_p4;
wire   [31:0] val_fu_248_p3;
wire   [0:0] p_Result_s_fu_134_p3;
wire   [31:0] result_V_29_fu_256_p2;
reg    grp_fu_62_ce;
reg    grp_fu_68_ce;
reg    grp_fu_72_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_78_ce;
wire   [31:0] result_V_fu_262_p3;
reg    ap_ce_reg;
reg   [31:0] d_int_reg;
reg   [31:0] ap_return_int_reg;

rrt_fmul_32ns_32ns_32_4_max_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_0_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d_int_reg),
    .din1(32'd1199570944),
    .ce(grp_fu_62_ce),
    .dout(grp_fu_62_p2)
);

rrt_fpext_32ns_64_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_0_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_62_p2),
    .ce(grp_fu_68_ce),
    .dout(grp_fu_68_p1)
);

rrt_fcmp_32ns_32ns_1_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_0_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d_int_reg),
    .din1(32'd0),
    .ce(grp_fu_72_ce),
    .opcode(5'd3),
    .dout(grp_fu_72_p2)
);

rrt_dadd_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_0_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_68_p1),
    .din1(grp_fu_78_p1),
    .ce(grp_fu_78_ce),
    .dout(grp_fu_78_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= result_V_fu_262_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        d_int_reg <= d;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        dc_reg_306 <= grp_fu_78_p2;
        icmp_ln7_2_reg_281 <= icmp_ln7_2_fu_107_p2;
        icmp_ln7_2_reg_281_pp0_iter1_reg <= icmp_ln7_2_reg_281;
        icmp_ln7_2_reg_281_pp0_iter2_reg <= icmp_ln7_2_reg_281_pp0_iter1_reg;
        icmp_ln7_2_reg_281_pp0_iter3_reg <= icmp_ln7_2_reg_281_pp0_iter2_reg;
        icmp_ln7_reg_276 <= icmp_ln7_fu_101_p2;
        icmp_ln7_reg_276_pp0_iter1_reg <= icmp_ln7_reg_276;
        icmp_ln7_reg_276_pp0_iter2_reg <= icmp_ln7_reg_276_pp0_iter1_reg;
        icmp_ln7_reg_276_pp0_iter3_reg <= icmp_ln7_reg_276_pp0_iter2_reg;
        tmp_5_reg_286 <= grp_fu_72_p2;
        tmp_5_reg_286_pp0_iter2_reg <= tmp_5_reg_286;
        tmp_5_reg_286_pp0_iter3_reg <= tmp_5_reg_286_pp0_iter2_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = result_V_fu_262_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_62_ce = 1'b1;
    end else begin
        grp_fu_62_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_68_ce = 1'b1;
    end else begin
        grp_fu_68_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_72_ce = 1'b1;
    end else begin
        grp_fu_72_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_78_ce = 1'b1;
    end else begin
        grp_fu_78_ce = 1'b0;
    end
end

assign add_ln513_fu_174_p2 = ($signed(zext_ln513_fu_170_p1) + $signed(12'd3073));

assign and_ln7_fu_117_p2 = (tmp_5_reg_286_pp0_iter3_reg & or_ln7_fu_113_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign bitcast_ln7_fu_83_p1 = d_int_reg;

assign data_V_fu_131_p1 = dc_reg_306;

assign grp_fu_78_p1 = ((and_ln7_fu_117_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign icmp_ln7_2_fu_107_p2 = ((trunc_ln7_fu_97_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_101_p2 = ((tmp_s_fu_87_p4 != 8'd255) ? 1'b1 : 1'b0);

assign isNeg_fu_180_p3 = add_ln513_fu_174_p2[32'd11];

assign mantissa_fu_156_p4 = {{{{1'd1}, {tmp_56_fu_152_p1}}}, {1'd0}};

assign or_ln7_fu_113_p2 = (icmp_ln7_reg_276_pp0_iter3_reg | icmp_ln7_2_reg_281_pp0_iter3_reg);

assign p_Result_s_fu_134_p3 = data_V_fu_131_p1[32'd63];

assign r_V_15_fu_220_p2 = zext_ln15_fu_166_p1 << zext_ln1340_fu_210_p1;

assign r_V_fu_214_p2 = zext_ln15_fu_166_p1 >> zext_ln1340_fu_210_p1;

assign result_V_29_fu_256_p2 = (32'd0 - val_fu_248_p3);

assign result_V_fu_262_p3 = ((p_Result_s_fu_134_p3[0:0] == 1'b1) ? result_V_29_fu_256_p2 : val_fu_248_p3);

assign sext_ln1340_fu_206_p1 = $signed(ush_fu_198_p3);

assign sext_ln1364_fu_194_p1 = $signed(sub_ln1364_fu_188_p2);

assign sub_ln1364_fu_188_p2 = (11'd1023 - tmp_55_fu_142_p4);

assign tmp_10_fu_238_p4 = {{r_V_15_fu_220_p2[84:53]}};

assign tmp_55_fu_142_p4 = {{data_V_fu_131_p1[62:52]}};

assign tmp_56_fu_152_p1 = data_V_fu_131_p1[51:0];

assign tmp_fu_226_p3 = r_V_fu_214_p2[32'd53];

assign tmp_s_fu_87_p4 = {{bitcast_ln7_fu_83_p1[30:23]}};

assign trunc_ln7_fu_97_p1 = bitcast_ln7_fu_83_p1[22:0];

assign ush_fu_198_p3 = ((isNeg_fu_180_p3[0:0] == 1'b1) ? sext_ln1364_fu_194_p1 : add_ln513_fu_174_p2);

assign val_fu_248_p3 = ((isNeg_fu_180_p3[0:0] == 1'b1) ? zext_ln671_fu_234_p1 : tmp_10_fu_238_p4);

assign zext_ln1340_fu_210_p1 = $unsigned(sext_ln1340_fu_206_p1);

assign zext_ln15_fu_166_p1 = mantissa_fu_156_p4;

assign zext_ln513_fu_170_p1 = tmp_55_fu_142_p4;

assign zext_ln671_fu_234_p1 = tmp_fu_226_p3;

endmodule //rrt_FloatToFixed_16ul_s
