// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_Nearhw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_near_address0,
        X_near_ce0,
        X_near_we0,
        X_near_d0,
        RRT_Star_Pos_0_0_address0,
        RRT_Star_Pos_0_0_ce0,
        RRT_Star_Pos_0_0_q0,
        RRT_Star_Pos_0_1_address0,
        RRT_Star_Pos_0_1_ce0,
        RRT_Star_Pos_0_1_q0,
        RRT_Star_Pos_1_address0,
        RRT_Star_Pos_1_ce0,
        RRT_Star_Pos_1_q0,
        p_read,
        p_read1,
        Squared_r_n,
        N,
        ap_return,
        grp_fu_515_p_din0,
        grp_fu_515_p_din1,
        grp_fu_515_p_opcode,
        grp_fu_515_p_dout0,
        grp_fu_515_p_ce,
        grp_fu_519_p_din0,
        grp_fu_519_p_din1,
        grp_fu_519_p_opcode,
        grp_fu_519_p_dout0,
        grp_fu_519_p_ce,
        grp_fu_531_p_din0,
        grp_fu_531_p_dout0,
        grp_fu_531_p_ce,
        grp_fu_1694_p_din0,
        grp_fu_1694_p_dout0,
        grp_fu_1694_p_ce
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state17 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] X_near_address0;
output   X_near_ce0;
output   X_near_we0;
output  [15:0] X_near_d0;
output  [13:0] RRT_Star_Pos_0_0_address0;
output   RRT_Star_Pos_0_0_ce0;
input  [31:0] RRT_Star_Pos_0_0_q0;
output  [13:0] RRT_Star_Pos_0_1_address0;
output   RRT_Star_Pos_0_1_ce0;
input  [31:0] RRT_Star_Pos_0_1_q0;
output  [13:0] RRT_Star_Pos_1_address0;
output   RRT_Star_Pos_1_ce0;
input  [15:0] RRT_Star_Pos_1_q0;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] Squared_r_n;
input  [13:0] N;
output  [31:0] ap_return;
output  [31:0] grp_fu_515_p_din0;
output  [31:0] grp_fu_515_p_din1;
output  [0:0] grp_fu_515_p_opcode;
input  [31:0] grp_fu_515_p_dout0;
output   grp_fu_515_p_ce;
output  [31:0] grp_fu_519_p_din0;
output  [31:0] grp_fu_519_p_din1;
output  [0:0] grp_fu_519_p_opcode;
input  [31:0] grp_fu_519_p_dout0;
output   grp_fu_519_p_ce;
output  [31:0] grp_fu_531_p_din0;
input  [31:0] grp_fu_531_p_dout0;
output   grp_fu_531_p_ce;
output  [31:0] grp_fu_1694_p_din0;
input  [31:0] grp_fu_1694_p_dout0;
output   grp_fu_1694_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg X_near_ce0;
reg X_near_we0;
reg RRT_Star_Pos_0_0_ce0;
reg RRT_Star_Pos_0_1_ce0;
reg RRT_Star_Pos_1_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
reg   [31:0] conv_i_i_reg_616;
reg   [31:0] conv9_i_i_reg_621;
wire   [63:0] i_cast_fu_212_p1;
reg   [63:0] i_cast_reg_629;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
wire    ap_block_state9_pp0_stage0_iter5;
wire    ap_block_state10_pp0_stage0_iter6;
wire    ap_block_state11_pp0_stage0_iter7;
wire    ap_block_state12_pp0_stage0_iter8;
wire    ap_block_state13_pp0_stage0_iter9;
wire    ap_block_state14_pp0_stage0_iter10;
wire    ap_block_state15_pp0_stage0_iter11;
wire    ap_block_state16_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln159_fu_201_p2;
reg   [63:0] i_cast_reg_629_pp0_iter1_reg;
reg   [63:0] i_cast_reg_629_pp0_iter2_reg;
reg   [63:0] i_cast_reg_629_pp0_iter3_reg;
reg   [63:0] i_cast_reg_629_pp0_iter4_reg;
reg   [63:0] i_cast_reg_629_pp0_iter5_reg;
reg   [63:0] i_cast_reg_629_pp0_iter6_reg;
reg   [63:0] i_cast_reg_629_pp0_iter7_reg;
reg   [63:0] i_cast_reg_629_pp0_iter8_reg;
reg   [63:0] i_cast_reg_629_pp0_iter9_reg;
reg   [63:0] i_cast_reg_629_pp0_iter10_reg;
reg   [31:0] B_x_reg_644;
reg   [31:0] B_y_reg_649;
reg   [31:0] conv_i_i_i_reg_654;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] conv_i2_i_i_reg_659;
reg   [31:0] dc_reg_664;
reg   [31:0] dc_4_reg_669;
wire   [31:0] result_V_fu_354_p3;
reg   [31:0] result_V_reg_674;
wire   [31:0] result_V_27_fu_493_p3;
reg   [31:0] result_V_27_reg_679;
reg   [31:0] trunc_ln_reg_684;
reg   [31:0] trunc_ln34_6_reg_689;
wire   [0:0] icmp_ln167_fu_543_p2;
reg   [0:0] icmp_ln167_reg_694;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln169_fu_551_p1;
reg   [13:0] i_fu_78;
wire   [13:0] add_ln159_fu_206_p2;
reg   [31:0] empty_fu_82;
wire   [31:0] add_ln170_fu_556_p2;
reg   [31:0] X_near_count_0_fu_86;
wire    ap_CS_fsm_state17;
reg   [31:0] grp_fu_175_p0;
reg   [31:0] grp_fu_179_p0;
wire   [31:0] data_V_fu_223_p1;
wire   [22:0] tmp_52_fu_244_p1;
wire   [24:0] mantissa_fu_248_p4;
wire   [7:0] tmp_51_fu_234_p4;
wire   [8:0] zext_ln344_fu_262_p1;
wire   [8:0] add_ln344_fu_266_p2;
wire   [7:0] sub_ln1364_fu_280_p2;
wire   [0:0] isNeg_fu_272_p3;
wire  signed [8:0] sext_ln1364_fu_286_p1;
wire   [8:0] ush_fu_290_p3;
wire  signed [31:0] sext_ln1340_fu_298_p1;
wire   [78:0] zext_ln15_fu_258_p1;
wire   [78:0] zext_ln1340_fu_302_p1;
wire   [78:0] r_V_fu_306_p2;
wire   [0:0] tmp_fu_318_p3;
wire   [78:0] r_V_12_fu_312_p2;
wire   [31:0] zext_ln671_fu_326_p1;
wire   [31:0] tmp_s_fu_330_p4;
wire   [31:0] val_fu_340_p3;
wire   [0:0] p_Result_s_fu_226_p3;
wire   [31:0] result_V_23_fu_348_p2;
wire   [31:0] data_V_4_fu_362_p1;
wire   [22:0] tmp_54_fu_383_p1;
wire   [24:0] mantissa_3_fu_387_p4;
wire   [7:0] tmp_53_fu_373_p4;
wire   [8:0] zext_ln344_3_fu_401_p1;
wire   [8:0] add_ln344_3_fu_405_p2;
wire   [7:0] sub_ln1364_3_fu_419_p2;
wire   [0:0] isNeg_4_fu_411_p3;
wire  signed [8:0] sext_ln1364_3_fu_425_p1;
wire   [8:0] ush_4_fu_429_p3;
wire  signed [31:0] sext_ln1340_4_fu_437_p1;
wire   [78:0] zext_ln15_3_fu_397_p1;
wire   [78:0] zext_ln1340_4_fu_441_p1;
wire   [78:0] r_V_13_fu_445_p2;
wire   [0:0] tmp_50_fu_457_p3;
wire   [78:0] r_V_14_fu_451_p2;
wire   [31:0] zext_ln671_3_fu_465_p1;
wire   [31:0] tmp_8_fu_469_p4;
wire   [31:0] val_4_fu_479_p3;
wire   [0:0] p_Result_4_fu_365_p3;
wire   [31:0] result_V_26_fu_487_p2;
wire  signed [31:0] mul_ln34_fu_504_p0;
wire  signed [47:0] sext_ln34_fu_501_p1;
wire  signed [31:0] mul_ln34_fu_504_p1;
wire   [47:0] mul_ln34_fu_504_p2;
wire  signed [31:0] mul_ln34_7_fu_523_p0;
wire  signed [47:0] sext_ln34_7_fu_520_p1;
wire  signed [31:0] mul_ln34_7_fu_523_p1;
wire   [47:0] mul_ln34_7_fu_523_p2;
wire   [31:0] D_fu_539_p2;
wire    ap_block_pp0_stage0_00001;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
end

rrt_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U142(
    .din0(mul_ln34_fu_504_p0),
    .din1(mul_ln34_fu_504_p1),
    .dout(mul_ln34_fu_504_p2)
);

rrt_mul_32s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_32s_32s_48_1_1_U143(
    .din0(mul_ln34_7_fu_523_p0),
    .din1(mul_ln34_7_fu_523_p1),
    .dout(mul_ln34_7_fu_523_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state4)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter12 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        X_near_count_0_fu_86 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln167_reg_694 == 1'd1))) begin
        X_near_count_0_fu_86 <= add_ln170_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        empty_fu_82 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln167_reg_694 == 1'd1))) begin
        empty_fu_82 <= add_ln170_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_78 <= 14'd0;
    end else if (((icmp_ln159_fu_201_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_fu_78 <= add_ln159_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_x_reg_644 <= RRT_Star_Pos_0_0_q0;
        B_y_reg_649 <= RRT_Star_Pos_0_1_q0;
        i_cast_reg_629_pp0_iter1_reg[13 : 0] <= i_cast_reg_629[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        conv9_i_i_reg_621 <= grp_fu_1694_p_dout0;
        conv_i_i_reg_616 <= grp_fu_531_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv_i2_i_i_reg_659 <= grp_fu_1694_p_dout0;
        conv_i_i_i_reg_654 <= grp_fu_531_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        dc_4_reg_669 <= grp_fu_519_p_dout0;
        dc_reg_664 <= grp_fu_515_p_dout0;
        i_cast_reg_629_pp0_iter10_reg[13 : 0] <= i_cast_reg_629_pp0_iter9_reg[13 : 0];
        i_cast_reg_629_pp0_iter2_reg[13 : 0] <= i_cast_reg_629_pp0_iter1_reg[13 : 0];
        i_cast_reg_629_pp0_iter3_reg[13 : 0] <= i_cast_reg_629_pp0_iter2_reg[13 : 0];
        i_cast_reg_629_pp0_iter4_reg[13 : 0] <= i_cast_reg_629_pp0_iter3_reg[13 : 0];
        i_cast_reg_629_pp0_iter5_reg[13 : 0] <= i_cast_reg_629_pp0_iter4_reg[13 : 0];
        i_cast_reg_629_pp0_iter6_reg[13 : 0] <= i_cast_reg_629_pp0_iter5_reg[13 : 0];
        i_cast_reg_629_pp0_iter7_reg[13 : 0] <= i_cast_reg_629_pp0_iter6_reg[13 : 0];
        i_cast_reg_629_pp0_iter8_reg[13 : 0] <= i_cast_reg_629_pp0_iter7_reg[13 : 0];
        i_cast_reg_629_pp0_iter9_reg[13 : 0] <= i_cast_reg_629_pp0_iter8_reg[13 : 0];
        icmp_ln167_reg_694 <= icmp_ln167_fu_543_p2;
        result_V_27_reg_679 <= result_V_27_fu_493_p3;
        result_V_reg_674 <= result_V_fu_354_p3;
        trunc_ln34_6_reg_689 <= {{mul_ln34_7_fu_523_p2[47:16]}};
        trunc_ln_reg_684 <= {{mul_ln34_fu_504_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln159_fu_201_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_cast_reg_629[13 : 0] <= i_cast_fu_212_p1[13 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        RRT_Star_Pos_0_0_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        RRT_Star_Pos_0_1_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        RRT_Star_Pos_1_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        X_near_ce0 = 1'b1;
    end else begin
        X_near_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (icmp_ln167_reg_694 == 1'd1))) begin
        X_near_we0 = 1'b1;
    end else begin
        X_near_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln159_fu_201_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        grp_fu_175_p0 = B_x_reg_644;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_175_p0 = p_read;
    end else begin
        grp_fu_175_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        grp_fu_179_p0 = B_y_reg_649;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_179_p0 = p_read1;
    end else begin
        grp_fu_179_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln159_fu_201_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln159_fu_201_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D_fu_539_p2 = (trunc_ln34_6_reg_689 + trunc_ln_reg_684);

assign RRT_Star_Pos_0_0_address0 = i_cast_fu_212_p1;

assign RRT_Star_Pos_0_1_address0 = i_cast_fu_212_p1;

assign RRT_Star_Pos_1_address0 = i_cast_reg_629_pp0_iter10_reg;

assign X_near_address0 = zext_ln169_fu_551_p1;

assign X_near_d0 = RRT_Star_Pos_1_q0;

assign add_ln159_fu_206_p2 = (i_fu_78 + 14'd1);

assign add_ln170_fu_556_p2 = (empty_fu_82 + 32'd1);

assign add_ln344_3_fu_405_p2 = ($signed(zext_ln344_3_fu_401_p1) + $signed(9'd385));

assign add_ln344_fu_266_p2 = ($signed(zext_ln344_fu_262_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = X_near_count_0_fu_86;

assign data_V_4_fu_362_p1 = dc_4_reg_669;

assign data_V_fu_223_p1 = dc_reg_664;

assign grp_fu_1694_p_ce = 1'b1;

assign grp_fu_1694_p_din0 = grp_fu_179_p0;

assign grp_fu_515_p_ce = 1'b1;

assign grp_fu_515_p_din0 = conv_i_i_reg_616;

assign grp_fu_515_p_din1 = conv_i_i_i_reg_654;

assign grp_fu_515_p_opcode = 2'd1;

assign grp_fu_519_p_ce = 1'b1;

assign grp_fu_519_p_din0 = conv9_i_i_reg_621;

assign grp_fu_519_p_din1 = conv_i2_i_i_reg_659;

assign grp_fu_519_p_opcode = 2'd1;

assign grp_fu_531_p_ce = 1'b1;

assign grp_fu_531_p_din0 = grp_fu_175_p0;

assign i_cast_fu_212_p1 = i_fu_78;

assign icmp_ln159_fu_201_p2 = ((i_fu_78 == N) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_543_p2 = (($signed(D_fu_539_p2) < $signed(Squared_r_n)) ? 1'b1 : 1'b0);

assign isNeg_4_fu_411_p3 = add_ln344_3_fu_405_p2[32'd8];

assign isNeg_fu_272_p3 = add_ln344_fu_266_p2[32'd8];

assign mantissa_3_fu_387_p4 = {{{{1'd1}, {tmp_54_fu_383_p1}}}, {1'd0}};

assign mantissa_fu_248_p4 = {{{{1'd1}, {tmp_52_fu_244_p1}}}, {1'd0}};

assign mul_ln34_7_fu_523_p0 = sext_ln34_7_fu_520_p1;

assign mul_ln34_7_fu_523_p1 = sext_ln34_7_fu_520_p1;

assign mul_ln34_fu_504_p0 = sext_ln34_fu_501_p1;

assign mul_ln34_fu_504_p1 = sext_ln34_fu_501_p1;

assign p_Result_4_fu_365_p3 = data_V_4_fu_362_p1[32'd31];

assign p_Result_s_fu_226_p3 = data_V_fu_223_p1[32'd31];

assign r_V_12_fu_312_p2 = zext_ln15_fu_258_p1 << zext_ln1340_fu_302_p1;

assign r_V_13_fu_445_p2 = zext_ln15_3_fu_397_p1 >> zext_ln1340_4_fu_441_p1;

assign r_V_14_fu_451_p2 = zext_ln15_3_fu_397_p1 << zext_ln1340_4_fu_441_p1;

assign r_V_fu_306_p2 = zext_ln15_fu_258_p1 >> zext_ln1340_fu_302_p1;

assign result_V_23_fu_348_p2 = (32'd0 - val_fu_340_p3);

assign result_V_26_fu_487_p2 = (32'd0 - val_4_fu_479_p3);

assign result_V_27_fu_493_p3 = ((p_Result_4_fu_365_p3[0:0] == 1'b1) ? result_V_26_fu_487_p2 : val_4_fu_479_p3);

assign result_V_fu_354_p3 = ((p_Result_s_fu_226_p3[0:0] == 1'b1) ? result_V_23_fu_348_p2 : val_fu_340_p3);

assign sext_ln1340_4_fu_437_p1 = $signed(ush_4_fu_429_p3);

assign sext_ln1340_fu_298_p1 = $signed(ush_fu_290_p3);

assign sext_ln1364_3_fu_425_p1 = $signed(sub_ln1364_3_fu_419_p2);

assign sext_ln1364_fu_286_p1 = $signed(sub_ln1364_fu_280_p2);

assign sext_ln34_7_fu_520_p1 = $signed(result_V_27_reg_679);

assign sext_ln34_fu_501_p1 = $signed(result_V_reg_674);

assign sub_ln1364_3_fu_419_p2 = (8'd127 - tmp_53_fu_373_p4);

assign sub_ln1364_fu_280_p2 = (8'd127 - tmp_51_fu_234_p4);

assign tmp_50_fu_457_p3 = r_V_13_fu_445_p2[32'd24];

assign tmp_51_fu_234_p4 = {{data_V_fu_223_p1[30:23]}};

assign tmp_52_fu_244_p1 = data_V_fu_223_p1[22:0];

assign tmp_53_fu_373_p4 = {{data_V_4_fu_362_p1[30:23]}};

assign tmp_54_fu_383_p1 = data_V_4_fu_362_p1[22:0];

assign tmp_8_fu_469_p4 = {{r_V_14_fu_451_p2[55:24]}};

assign tmp_fu_318_p3 = r_V_fu_306_p2[32'd24];

assign tmp_s_fu_330_p4 = {{r_V_12_fu_312_p2[55:24]}};

assign ush_4_fu_429_p3 = ((isNeg_4_fu_411_p3[0:0] == 1'b1) ? sext_ln1364_3_fu_425_p1 : add_ln344_3_fu_405_p2);

assign ush_fu_290_p3 = ((isNeg_fu_272_p3[0:0] == 1'b1) ? sext_ln1364_fu_286_p1 : add_ln344_fu_266_p2);

assign val_4_fu_479_p3 = ((isNeg_4_fu_411_p3[0:0] == 1'b1) ? zext_ln671_3_fu_465_p1 : tmp_8_fu_469_p4);

assign val_fu_340_p3 = ((isNeg_fu_272_p3[0:0] == 1'b1) ? zext_ln671_fu_326_p1 : tmp_s_fu_330_p4);

assign zext_ln1340_4_fu_441_p1 = $unsigned(sext_ln1340_4_fu_437_p1);

assign zext_ln1340_fu_302_p1 = $unsigned(sext_ln1340_fu_298_p1);

assign zext_ln15_3_fu_397_p1 = mantissa_3_fu_387_p4;

assign zext_ln15_fu_258_p1 = mantissa_fu_248_p4;

assign zext_ln169_fu_551_p1 = empty_fu_82;

assign zext_ln344_3_fu_401_p1 = tmp_53_fu_373_p4;

assign zext_ln344_fu_262_p1 = tmp_51_fu_234_p4;

assign zext_ln671_3_fu_465_p1 = tmp_50_fu_457_p3;

assign zext_ln671_fu_326_p1 = tmp_fu_318_p3;

always @ (posedge ap_clk) begin
    i_cast_reg_629[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter4_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter5_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter6_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter7_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter8_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter9_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_629_pp0_iter10_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //rrt_Nearhw
