#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("dataInStream_TDATA", 64, hls_in, 0, "axis", "in_data", 1),
	Port_Property("dataInStream_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("dataInStream_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("dataInStream_TKEEP", 8, hls_in, 1, "axis", "in_data", 1),
	Port_Property("dataInStream_TSTRB", 8, hls_in, 2, "axis", "in_data", 1),
	Port_Property("dataInStream_TUSER", 2, hls_in, 3, "axis", "in_data", 1),
	Port_Property("dataInStream_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("dataInStream_TID", 5, hls_in, 5, "axis", "in_data", 1),
	Port_Property("dataInStream_TDEST", 6, hls_in, 6, "axis", "in_data", 1),
	Port_Property("XNearStream_TDATA", 32, hls_out, 13, "axis", "out_data", 1),
	Port_Property("XNearStream_TVALID", 1, hls_out, 19, "axis", "out_vld", 1),
	Port_Property("XNearStream_TREADY", 1, hls_in, 19, "axis", "out_acc", 1),
	Port_Property("XNearStream_TKEEP", 4, hls_out, 14, "axis", "out_data", 1),
	Port_Property("XNearStream_TSTRB", 4, hls_out, 15, "axis", "out_data", 1),
	Port_Property("XNearStream_TUSER", 2, hls_out, 16, "axis", "out_data", 1),
	Port_Property("XNearStream_TLAST", 1, hls_out, 17, "axis", "out_data", 1),
	Port_Property("XNearStream_TID", 5, hls_out, 18, "axis", "out_data", 1),
	Port_Property("XNearStream_TDEST", 6, hls_out, 19, "axis", "out_data", 1),
	Port_Property("s_axi_CTRL_BUS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_AWADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "rrt";
