-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rrt_rrt_Pipeline_VITIS_LOOP_240_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Edges_AABB_3_0172_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    Edges_AABB_3_0172_out_ap_vld : OUT STD_LOGIC;
    Edges_AABB_2_0171_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    Edges_AABB_2_0171_out_ap_vld : OUT STD_LOGIC;
    Edges_AABB_1_0170_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    Edges_AABB_1_0170_out_ap_vld : OUT STD_LOGIC;
    Edges_AABB_0_0169_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    Edges_AABB_0_0169_out_ap_vld : OUT STD_LOGIC;
    grp_fu_562_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_562_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_562_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_562_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_562_p_ce : OUT STD_LOGIC;
    grp_fu_566_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_566_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_566_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_566_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_566_p_ce : OUT STD_LOGIC;
    grp_fu_575_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_575_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_575_p_ce : OUT STD_LOGIC;
    grp_fu_578_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_578_p_ce : OUT STD_LOGIC;
    grp_fu_1013_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1013_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1013_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_1013_p_ce : OUT STD_LOGIC;
    grp_fu_1022_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1022_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1022_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_1022_p_ce : OUT STD_LOGIC );
end;


architecture behav of rrt_rrt_Pipeline_VITIS_LOOP_240_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_A0000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000010100000000000000000";
    constant ap_const_lv32_FFF60000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111101100000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln240_fu_157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln240_reg_595 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln240_reg_595_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln31_fu_169_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln31_reg_599_pp0_iter24_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_173_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_603 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_187_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_608 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_201_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_613 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_i_reg_618 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_i1_reg_623 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_146_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_i3_reg_629 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_634 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_2_reg_639 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_reg_644 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_644_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_241_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_24_reg_649 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_fu_255_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_654 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_273_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_reg_659 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_2_reg_664 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_reg_664_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_302_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_26_reg_669 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_2_fu_316_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_2_reg_674 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_2_fu_334_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_2_reg_679 : STD_LOGIC_VECTOR (8 downto 0);
    signal val_fu_396_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_684 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_2_fu_457_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_2_reg_690 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_11_fu_469_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_11_reg_696 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_fu_480_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_reg_701 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln34_fu_486_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln34_1_fu_495_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln1_reg_718 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln34_1_reg_723 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_84 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln240_fu_163_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal Edges_AABB_0_0169_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln244_fu_524_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Edges_AABB_1_0170_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal Edges_AABB_2_0171_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal Edges_AABB_3_0172_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal data_V_fu_220_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_231_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_fu_245_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln344_fu_249_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1364_fu_263_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1364_fu_269_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_V_2_fu_281_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_292_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_1_fu_306_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln344_1_fu_310_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1364_1_fu_324_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1364_1_fu_330_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_fu_342_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1340_fu_355_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_351_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1340_fu_358_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_fu_362_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_16_fu_374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_4_fu_368_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln671_fu_382_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_386_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal mantissa_1_fu_403_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1340_2_fu_416_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_1_fu_412_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1340_2_fu_419_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_5_fu_423_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_22_fu_435_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_6_fu_429_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln671_1_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_447_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_8_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_9_fu_475_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component rrt_fsub_32ns_32ns_32_9_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_sitofp_32ns_32_7_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_mux_42_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_mul_32s_32s_48_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component rrt_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sitofp_32ns_32_7_no_dsp_1_U5 : component rrt_sitofp_32ns_32_7_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_5_reg_613,
        ce => ap_const_logic_1,
        dout => grp_fu_146_p1);

    mux_42_32_1_1_U6 : component rrt_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_A0000,
        din1 => ap_const_lv32_FFF60000,
        din2 => ap_const_lv32_FFF60000,
        din3 => ap_const_lv32_A0000,
        din4 => trunc_ln31_fu_169_p1,
        dout => tmp_fu_173_p6);

    mux_42_32_1_1_U7 : component rrt_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_A0000,
        din1 => ap_const_lv32_A0000,
        din2 => ap_const_lv32_FFF60000,
        din3 => ap_const_lv32_FFF60000,
        din4 => trunc_ln31_fu_169_p1,
        dout => tmp_1_fu_187_p6);

    mux_42_32_1_1_U8 : component rrt_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_FFF60000,
        din1 => ap_const_lv32_A0000,
        din2 => ap_const_lv32_A0000,
        din3 => ap_const_lv32_FFF60000,
        din4 => trunc_ln31_fu_169_p1,
        dout => tmp_5_fu_201_p6);

    flow_control_loop_pipe_sequential_init_U : component rrt_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter24_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln240_fu_157_p2 = ap_const_lv1_0))) then 
                    i_fu_84 <= add_ln240_fu_163_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (trunc_ln31_reg_599_pp0_iter24_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Edges_AABB_0_0169_fu_88 <= add_ln244_fu_524_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (trunc_ln31_reg_599_pp0_iter24_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Edges_AABB_1_0170_fu_92 <= add_ln244_fu_524_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (trunc_ln31_reg_599_pp0_iter24_reg = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Edges_AABB_2_0171_fu_96 <= add_ln244_fu_524_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (trunc_ln31_reg_599_pp0_iter24_reg = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Edges_AABB_3_0172_fu_100 <= add_ln244_fu_524_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv_i1_reg_623 <= grp_fu_578_p_dout0;
                conv_i3_reg_629 <= grp_fu_146_p1;
                conv_i_reg_618 <= grp_fu_575_p_dout0;
                dc_2_reg_639 <= grp_fu_566_p_dout0;
                dc_reg_634 <= grp_fu_562_p_dout0;
                icmp_ln240_reg_595_pp0_iter10_reg <= icmp_ln240_reg_595_pp0_iter9_reg;
                icmp_ln240_reg_595_pp0_iter11_reg <= icmp_ln240_reg_595_pp0_iter10_reg;
                icmp_ln240_reg_595_pp0_iter12_reg <= icmp_ln240_reg_595_pp0_iter11_reg;
                icmp_ln240_reg_595_pp0_iter13_reg <= icmp_ln240_reg_595_pp0_iter12_reg;
                icmp_ln240_reg_595_pp0_iter14_reg <= icmp_ln240_reg_595_pp0_iter13_reg;
                icmp_ln240_reg_595_pp0_iter15_reg <= icmp_ln240_reg_595_pp0_iter14_reg;
                icmp_ln240_reg_595_pp0_iter16_reg <= icmp_ln240_reg_595_pp0_iter15_reg;
                icmp_ln240_reg_595_pp0_iter17_reg <= icmp_ln240_reg_595_pp0_iter16_reg;
                icmp_ln240_reg_595_pp0_iter18_reg <= icmp_ln240_reg_595_pp0_iter17_reg;
                icmp_ln240_reg_595_pp0_iter19_reg <= icmp_ln240_reg_595_pp0_iter18_reg;
                icmp_ln240_reg_595_pp0_iter20_reg <= icmp_ln240_reg_595_pp0_iter19_reg;
                icmp_ln240_reg_595_pp0_iter21_reg <= icmp_ln240_reg_595_pp0_iter20_reg;
                icmp_ln240_reg_595_pp0_iter22_reg <= icmp_ln240_reg_595_pp0_iter21_reg;
                icmp_ln240_reg_595_pp0_iter23_reg <= icmp_ln240_reg_595_pp0_iter22_reg;
                icmp_ln240_reg_595_pp0_iter2_reg <= icmp_ln240_reg_595_pp0_iter1_reg;
                icmp_ln240_reg_595_pp0_iter3_reg <= icmp_ln240_reg_595_pp0_iter2_reg;
                icmp_ln240_reg_595_pp0_iter4_reg <= icmp_ln240_reg_595_pp0_iter3_reg;
                icmp_ln240_reg_595_pp0_iter5_reg <= icmp_ln240_reg_595_pp0_iter4_reg;
                icmp_ln240_reg_595_pp0_iter6_reg <= icmp_ln240_reg_595_pp0_iter5_reg;
                icmp_ln240_reg_595_pp0_iter7_reg <= icmp_ln240_reg_595_pp0_iter6_reg;
                icmp_ln240_reg_595_pp0_iter8_reg <= icmp_ln240_reg_595_pp0_iter7_reg;
                icmp_ln240_reg_595_pp0_iter9_reg <= icmp_ln240_reg_595_pp0_iter8_reg;
                isNeg_2_reg_674 <= add_ln344_1_fu_310_p2(8 downto 8);
                isNeg_reg_654 <= add_ln344_fu_249_p2(8 downto 8);
                p_Result_2_reg_664 <= data_V_2_fu_281_p1(31 downto 31);
                p_Result_2_reg_664_pp0_iter18_reg <= p_Result_2_reg_664;
                p_Result_s_reg_644 <= data_V_fu_220_p1(31 downto 31);
                p_Result_s_reg_644_pp0_iter18_reg <= p_Result_s_reg_644;
                result_V_11_reg_696 <= result_V_11_fu_469_p3;
                result_V_reg_701 <= result_V_fu_480_p3;
                tmp_24_reg_649 <= tmp_24_fu_241_p1;
                tmp_26_reg_669 <= tmp_26_fu_302_p1;
                trunc_ln1_reg_718 <= grp_fu_1013_p_dout0(47 downto 16);
                trunc_ln31_reg_599_pp0_iter10_reg <= trunc_ln31_reg_599_pp0_iter9_reg;
                trunc_ln31_reg_599_pp0_iter11_reg <= trunc_ln31_reg_599_pp0_iter10_reg;
                trunc_ln31_reg_599_pp0_iter12_reg <= trunc_ln31_reg_599_pp0_iter11_reg;
                trunc_ln31_reg_599_pp0_iter13_reg <= trunc_ln31_reg_599_pp0_iter12_reg;
                trunc_ln31_reg_599_pp0_iter14_reg <= trunc_ln31_reg_599_pp0_iter13_reg;
                trunc_ln31_reg_599_pp0_iter15_reg <= trunc_ln31_reg_599_pp0_iter14_reg;
                trunc_ln31_reg_599_pp0_iter16_reg <= trunc_ln31_reg_599_pp0_iter15_reg;
                trunc_ln31_reg_599_pp0_iter17_reg <= trunc_ln31_reg_599_pp0_iter16_reg;
                trunc_ln31_reg_599_pp0_iter18_reg <= trunc_ln31_reg_599_pp0_iter17_reg;
                trunc_ln31_reg_599_pp0_iter19_reg <= trunc_ln31_reg_599_pp0_iter18_reg;
                trunc_ln31_reg_599_pp0_iter20_reg <= trunc_ln31_reg_599_pp0_iter19_reg;
                trunc_ln31_reg_599_pp0_iter21_reg <= trunc_ln31_reg_599_pp0_iter20_reg;
                trunc_ln31_reg_599_pp0_iter22_reg <= trunc_ln31_reg_599_pp0_iter21_reg;
                trunc_ln31_reg_599_pp0_iter23_reg <= trunc_ln31_reg_599_pp0_iter22_reg;
                trunc_ln31_reg_599_pp0_iter24_reg <= trunc_ln31_reg_599_pp0_iter23_reg;
                trunc_ln31_reg_599_pp0_iter2_reg <= trunc_ln31_reg_599_pp0_iter1_reg;
                trunc_ln31_reg_599_pp0_iter3_reg <= trunc_ln31_reg_599_pp0_iter2_reg;
                trunc_ln31_reg_599_pp0_iter4_reg <= trunc_ln31_reg_599_pp0_iter3_reg;
                trunc_ln31_reg_599_pp0_iter5_reg <= trunc_ln31_reg_599_pp0_iter4_reg;
                trunc_ln31_reg_599_pp0_iter6_reg <= trunc_ln31_reg_599_pp0_iter5_reg;
                trunc_ln31_reg_599_pp0_iter7_reg <= trunc_ln31_reg_599_pp0_iter6_reg;
                trunc_ln31_reg_599_pp0_iter8_reg <= trunc_ln31_reg_599_pp0_iter7_reg;
                trunc_ln31_reg_599_pp0_iter9_reg <= trunc_ln31_reg_599_pp0_iter8_reg;
                trunc_ln34_1_reg_723 <= grp_fu_1022_p_dout0(47 downto 16);
                ush_2_reg_679 <= ush_2_fu_334_p3;
                ush_reg_659 <= ush_fu_273_p3;
                val_2_reg_690 <= val_2_fu_457_p3;
                val_reg_684 <= val_fu_396_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln240_reg_595 <= icmp_ln240_fu_157_p2;
                icmp_ln240_reg_595_pp0_iter1_reg <= icmp_ln240_reg_595;
                trunc_ln31_reg_599_pp0_iter1_reg <= trunc_ln31_reg_599;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln240_fu_157_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_1_reg_608 <= tmp_1_fu_187_p6;
                tmp_5_reg_613 <= tmp_5_fu_201_p6;
                tmp_reg_603 <= tmp_fu_173_p6;
                trunc_ln31_reg_599 <= trunc_ln31_fu_169_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Edges_AABB_0_0169_out <= Edges_AABB_0_0169_fu_88;

    Edges_AABB_0_0169_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln240_reg_595_pp0_iter23_reg)
    begin
        if (((icmp_ln240_reg_595_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Edges_AABB_0_0169_out_ap_vld <= ap_const_logic_1;
        else 
            Edges_AABB_0_0169_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Edges_AABB_1_0170_out <= Edges_AABB_1_0170_fu_92;

    Edges_AABB_1_0170_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln240_reg_595_pp0_iter23_reg)
    begin
        if (((icmp_ln240_reg_595_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Edges_AABB_1_0170_out_ap_vld <= ap_const_logic_1;
        else 
            Edges_AABB_1_0170_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Edges_AABB_2_0171_out <= Edges_AABB_2_0171_fu_96;

    Edges_AABB_2_0171_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln240_reg_595_pp0_iter23_reg)
    begin
        if (((icmp_ln240_reg_595_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Edges_AABB_2_0171_out_ap_vld <= ap_const_logic_1;
        else 
            Edges_AABB_2_0171_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Edges_AABB_3_0172_out <= Edges_AABB_3_0172_fu_100;

    Edges_AABB_3_0172_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln240_reg_595_pp0_iter23_reg)
    begin
        if (((icmp_ln240_reg_595_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Edges_AABB_3_0172_out_ap_vld <= ap_const_logic_1;
        else 
            Edges_AABB_3_0172_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln240_fu_163_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv3_1));
    add_ln244_fu_524_p2 <= std_logic_vector(unsigned(trunc_ln34_1_reg_723) + unsigned(trunc_ln1_reg_718));
    add_ln344_1_fu_310_p2 <= std_logic_vector(unsigned(zext_ln344_1_fu_306_p1) + unsigned(ap_const_lv9_181));
    add_ln344_fu_249_p2 <= std_logic_vector(unsigned(zext_ln344_fu_245_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln240_fu_157_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln240_fu_157_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter24_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter24_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25)
    begin
        if (((ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_84, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_84;
        end if; 
    end process;

    data_V_2_fu_281_p1 <= dc_2_reg_639;
    data_V_fu_220_p1 <= dc_reg_634;
    grp_fu_1013_p_ce <= ap_const_logic_1;
    grp_fu_1013_p_din0 <= sext_ln34_fu_486_p1(32 - 1 downto 0);
    grp_fu_1013_p_din1 <= sext_ln34_fu_486_p1(32 - 1 downto 0);
    grp_fu_1022_p_ce <= ap_const_logic_1;
    grp_fu_1022_p_din0 <= sext_ln34_1_fu_495_p1(32 - 1 downto 0);
    grp_fu_1022_p_din1 <= sext_ln34_1_fu_495_p1(32 - 1 downto 0);
    grp_fu_562_p_ce <= ap_const_logic_1;
    grp_fu_562_p_din0 <= conv_i_reg_618;
    grp_fu_562_p_din1 <= conv_i1_reg_623;
    grp_fu_562_p_opcode <= ap_const_lv2_1;
    grp_fu_566_p_ce <= ap_const_logic_1;
    grp_fu_566_p_din0 <= conv_i1_reg_623;
    grp_fu_566_p_din1 <= conv_i3_reg_629;
    grp_fu_566_p_opcode <= ap_const_lv2_1;
    grp_fu_575_p_ce <= ap_const_logic_1;
    grp_fu_575_p_din0 <= tmp_reg_603;
    grp_fu_578_p_ce <= ap_const_logic_1;
    grp_fu_578_p_din0 <= tmp_1_reg_608;
    icmp_ln240_fu_157_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv3_4) else "0";
    isNeg_2_fu_316_p3 <= add_ln344_1_fu_310_p2(8 downto 8);
    isNeg_fu_255_p3 <= add_ln344_fu_249_p2(8 downto 8);
    mantissa_1_fu_403_p4 <= ((ap_const_lv1_1 & tmp_26_reg_669) & ap_const_lv1_0);
    mantissa_fu_342_p4 <= ((ap_const_lv1_1 & tmp_24_reg_649) & ap_const_lv1_0);
    r_V_4_fu_368_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_351_p1),to_integer(unsigned('0' & zext_ln1340_fu_358_p1(31-1 downto 0)))));
    r_V_5_fu_423_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_1_fu_412_p1),to_integer(unsigned('0' & zext_ln1340_2_fu_419_p1(31-1 downto 0)))));
    r_V_6_fu_429_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_1_fu_412_p1),to_integer(unsigned('0' & zext_ln1340_2_fu_419_p1(31-1 downto 0)))));
    r_V_fu_362_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_351_p1),to_integer(unsigned('0' & zext_ln1340_fu_358_p1(31-1 downto 0)))));
    result_V_11_fu_469_p3 <= 
        result_V_8_fu_464_p2 when (p_Result_s_reg_644_pp0_iter18_reg(0) = '1') else 
        val_reg_684;
    result_V_8_fu_464_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_reg_684));
    result_V_9_fu_475_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_2_reg_690));
    result_V_fu_480_p3 <= 
        result_V_9_fu_475_p2 when (p_Result_2_reg_664_pp0_iter18_reg(0) = '1') else 
        val_2_reg_690;
        sext_ln1340_2_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_2_reg_679),32));

        sext_ln1340_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_659),32));

        sext_ln1364_1_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_1_fu_324_p2),9));

        sext_ln1364_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_263_p2),9));

        sext_ln34_1_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_V_reg_701),48));

        sext_ln34_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_V_11_reg_696),48));

    sub_ln1364_1_fu_324_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_25_fu_292_p4));
    sub_ln1364_fu_263_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(tmp_23_fu_231_p4));
    tmp_16_fu_374_p3 <= r_V_fu_362_p2(24 downto 24);
    tmp_22_fu_435_p3 <= r_V_5_fu_423_p2(24 downto 24);
    tmp_23_fu_231_p4 <= data_V_fu_220_p1(30 downto 23);
    tmp_24_fu_241_p1 <= data_V_fu_220_p1(23 - 1 downto 0);
    tmp_25_fu_292_p4 <= data_V_2_fu_281_p1(30 downto 23);
    tmp_26_fu_302_p1 <= data_V_2_fu_281_p1(23 - 1 downto 0);
    tmp_7_fu_386_p4 <= r_V_4_fu_368_p2(55 downto 24);
    tmp_s_fu_447_p4 <= r_V_6_fu_429_p2(55 downto 24);
    trunc_ln31_fu_169_p1 <= ap_sig_allocacmp_i_2(2 - 1 downto 0);
    ush_2_fu_334_p3 <= 
        sext_ln1364_1_fu_330_p1 when (isNeg_2_fu_316_p3(0) = '1') else 
        add_ln344_1_fu_310_p2;
    ush_fu_273_p3 <= 
        sext_ln1364_fu_269_p1 when (isNeg_fu_255_p3(0) = '1') else 
        add_ln344_fu_249_p2;
    val_2_fu_457_p3 <= 
        zext_ln671_1_fu_443_p1 when (isNeg_2_reg_674(0) = '1') else 
        tmp_s_fu_447_p4;
    val_fu_396_p3 <= 
        zext_ln671_fu_382_p1 when (isNeg_reg_654(0) = '1') else 
        tmp_7_fu_386_p4;
    zext_ln1340_2_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_2_fu_416_p1),79));
    zext_ln1340_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_355_p1),79));
    zext_ln15_1_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_1_fu_403_p4),79));
    zext_ln15_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_342_p4),79));
    zext_ln344_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_292_p4),9));
    zext_ln344_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_231_p4),9));
    zext_ln671_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_435_p3),32));
    zext_ln671_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_374_p3),32));
end behav;
