-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rrt_FloatToFixed_16ul_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of rrt_FloatToFixed_16ul_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_47800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000111100000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv64_3FE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_BFE0000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111100000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";

attribute shreg_extract : string;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln7_fu_101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_276_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_276_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_reg_276_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_fu_107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_281 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_281_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_281_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln7_2_reg_281_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_286 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_286_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_286_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_62_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_68_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_78_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal dc_reg_306 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_78_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln7_fu_83_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_87_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln7_fu_97_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln7_fu_113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_fu_117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_fu_131_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_56_fu_152_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal mantissa_fu_156_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_55_fu_142_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln513_fu_170_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln513_fu_174_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1364_fu_188_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal isNeg_fu_180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1364_fu_194_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ush_fu_198_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1340_fu_206_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_166_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln1340_fu_210_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_fu_214_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_15_fu_220_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln671_fu_234_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_238_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_248_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_134_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_V_29_fu_256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_62_ce : STD_LOGIC;
    signal grp_fu_68_ce : STD_LOGIC;
    signal grp_fu_72_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal grp_fu_78_ce : STD_LOGIC;
    signal result_V_fu_262_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal d_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);

    component rrt_fmul_32ns_32ns_32_4_max_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rrt_fpext_32ns_64_2_no_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rrt_fcmp_32ns_32ns_1_2_no_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component rrt_dadd_64ns_64ns_64_5_full_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    fmul_32ns_32ns_32_4_max_dsp_0_U19 : component rrt_fmul_32ns_32ns_32_4_max_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => d_int_reg,
        din1 => ap_const_lv32_47800000,
        ce => grp_fu_62_ce,
        dout => grp_fu_62_p2);

    fpext_32ns_64_2_no_dsp_0_U20 : component rrt_fpext_32ns_64_2_no_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_62_p2,
        ce => grp_fu_68_ce,
        dout => grp_fu_68_p1);

    fcmp_32ns_32ns_1_2_no_dsp_0_U21 : component rrt_fcmp_32ns_32ns_1_2_no_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => d_int_reg,
        din1 => ap_const_lv32_0,
        ce => grp_fu_72_ce,
        opcode => ap_const_lv5_3,
        dout => grp_fu_72_p2);

    dadd_64ns_64ns_64_5_full_dsp_0_U22 : component rrt_dadd_64ns_64ns_64_5_full_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_68_p1,
        din1 => grp_fu_78_p1,
        ce => grp_fu_78_ce,
        dout => grp_fu_78_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= result_V_fu_262_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                d_int_reg <= d;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                dc_reg_306 <= grp_fu_78_p2;
                icmp_ln7_2_reg_281 <= icmp_ln7_2_fu_107_p2;
                icmp_ln7_2_reg_281_pp0_iter1_reg <= icmp_ln7_2_reg_281;
                icmp_ln7_2_reg_281_pp0_iter2_reg <= icmp_ln7_2_reg_281_pp0_iter1_reg;
                icmp_ln7_2_reg_281_pp0_iter3_reg <= icmp_ln7_2_reg_281_pp0_iter2_reg;
                icmp_ln7_reg_276 <= icmp_ln7_fu_101_p2;
                icmp_ln7_reg_276_pp0_iter1_reg <= icmp_ln7_reg_276;
                icmp_ln7_reg_276_pp0_iter2_reg <= icmp_ln7_reg_276_pp0_iter1_reg;
                icmp_ln7_reg_276_pp0_iter3_reg <= icmp_ln7_reg_276_pp0_iter2_reg;
                tmp_5_reg_286 <= grp_fu_72_p2;
                tmp_5_reg_286_pp0_iter2_reg <= tmp_5_reg_286;
                tmp_5_reg_286_pp0_iter3_reg <= tmp_5_reg_286_pp0_iter2_reg;
            end if;
        end if;
    end process;
    add_ln513_fu_174_p2 <= std_logic_vector(unsigned(zext_ln513_fu_170_p1) + unsigned(ap_const_lv12_C01));
    and_ln7_fu_117_p2 <= (tmp_5_reg_286_pp0_iter3_reg and or_ln7_fu_113_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(result_V_fu_262_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= result_V_fu_262_p3;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bitcast_ln7_fu_83_p1 <= d_int_reg;
    data_V_fu_131_p1 <= dc_reg_306;

    grp_fu_62_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_62_ce <= ap_const_logic_1;
        else 
            grp_fu_62_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_68_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_68_ce <= ap_const_logic_1;
        else 
            grp_fu_68_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_72_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_72_ce <= ap_const_logic_1;
        else 
            grp_fu_72_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_78_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_78_ce <= ap_const_logic_1;
        else 
            grp_fu_78_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_78_p1 <= 
        ap_const_lv64_3FE0000000000000 when (and_ln7_fu_117_p2(0) = '1') else 
        ap_const_lv64_BFE0000000000000;
    icmp_ln7_2_fu_107_p2 <= "1" when (trunc_ln7_fu_97_p1 = ap_const_lv23_0) else "0";
    icmp_ln7_fu_101_p2 <= "0" when (tmp_s_fu_87_p4 = ap_const_lv8_FF) else "1";
    isNeg_fu_180_p3 <= add_ln513_fu_174_p2(11 downto 11);
    mantissa_fu_156_p4 <= ((ap_const_lv1_1 & tmp_56_fu_152_p1) & ap_const_lv1_0);
    or_ln7_fu_113_p2 <= (icmp_ln7_reg_276_pp0_iter3_reg or icmp_ln7_2_reg_281_pp0_iter3_reg);
    p_Result_s_fu_134_p3 <= data_V_fu_131_p1(63 downto 63);
    r_V_15_fu_220_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_166_p1),to_integer(unsigned('0' & zext_ln1340_fu_210_p1(31-1 downto 0)))));
    r_V_fu_214_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_166_p1),to_integer(unsigned('0' & zext_ln1340_fu_210_p1(31-1 downto 0)))));
    result_V_29_fu_256_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_248_p3));
    result_V_fu_262_p3 <= 
        result_V_29_fu_256_p2 when (p_Result_s_fu_134_p3(0) = '1') else 
        val_fu_248_p3;
        sext_ln1340_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_198_p3),32));

        sext_ln1364_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_188_p2),12));

    sub_ln1364_fu_188_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(tmp_55_fu_142_p4));
    tmp_10_fu_238_p4 <= r_V_15_fu_220_p2(84 downto 53);
    tmp_55_fu_142_p4 <= data_V_fu_131_p1(62 downto 52);
    tmp_56_fu_152_p1 <= data_V_fu_131_p1(52 - 1 downto 0);
    tmp_fu_226_p3 <= r_V_fu_214_p2(53 downto 53);
    tmp_s_fu_87_p4 <= bitcast_ln7_fu_83_p1(30 downto 23);
    trunc_ln7_fu_97_p1 <= bitcast_ln7_fu_83_p1(23 - 1 downto 0);
    ush_fu_198_p3 <= 
        sext_ln1364_fu_194_p1 when (isNeg_fu_180_p3(0) = '1') else 
        add_ln513_fu_174_p2;
    val_fu_248_p3 <= 
        zext_ln671_fu_234_p1 when (isNeg_fu_180_p3(0) = '1') else 
        tmp_10_fu_238_p4;
    zext_ln1340_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_206_p1),137));
    zext_ln15_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_156_p4),137));
    zext_ln513_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_55_fu_142_p4),12));
    zext_ln671_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_226_p3),32));
end behav;
