// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_rrt_Pipeline_VITIS_LOOP_47_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Dist_sqr,
        q_out,
        q_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Dist_sqr;
output  [31:0] q_out;
output   q_out_ap_vld;

reg ap_idle;
reg q_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln47_fu_83_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [30:0] b_1_reg_212;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln47_reg_217;
reg   [31:0] q_load_reg_221;
wire   [31:0] b_cast_fu_92_p1;
reg   [31:0] b_cast_reg_226;
wire   [30:0] trunc_ln49_fu_96_p1;
reg   [30:0] trunc_ln49_reg_231;
wire   [31:0] t_fu_100_p2;
reg   [31:0] t_reg_236;
wire   [30:0] empty_38_fu_128_p1;
reg   [30:0] empty_38_reg_242;
wire   [0:0] xor_ln50_fu_141_p2;
reg   [0:0] xor_ln50_reg_247;
wire   [30:0] r_1_fu_147_p2;
reg   [30:0] r_1_reg_252;
wire   [31:0] q_2_fu_157_p3;
reg   [31:0] q_2_reg_257;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [31:0] r_fu_40;
wire   [31:0] r_2_fu_169_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [30:0] b_fu_44;
wire   [30:0] zext_ln56_fu_116_p1;
wire    ap_block_pp0_stage1;
reg   [31:0] q_fu_48;
reg   [31:0] ap_sig_allocacmp_q_load;
wire    ap_block_pp0_stage1_01001;
wire   [29:0] b_2_fu_106_p4;
wire   [0:0] icmp_ln50_fu_136_p2;
wire   [30:0] add_ln43_fu_132_p2;
wire   [31:0] q_1_fu_153_p2;
wire   [30:0] select_ln50_fu_164_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

rrt_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        b_fu_44 <= 31'd1073741824;
    end else if (((icmp_ln47_fu_83_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_fu_44 <= zext_ln56_fu_116_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        q_fu_48 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        q_fu_48 <= q_2_reg_257;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        r_fu_40 <= Dist_sqr;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        r_fu_40 <= r_2_fu_169_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_1_reg_212 <= b_fu_44;
        icmp_ln47_reg_217 <= icmp_ln47_fu_83_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_83_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_cast_reg_226[30 : 0] <= b_cast_fu_92_p1[30 : 0];
        q_load_reg_221 <= ap_sig_allocacmp_q_load;
        t_reg_236 <= t_fu_100_p2;
        trunc_ln49_reg_231 <= trunc_ln49_fu_96_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_reg_217 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_38_reg_242 <= empty_38_fu_128_p1;
        q_2_reg_257 <= q_2_fu_157_p3;
        r_1_reg_252 <= r_1_fu_147_p2;
        xor_ln50_reg_247 <= xor_ln50_fu_141_p2;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_83_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_q_load = q_2_reg_257;
    end else begin
        ap_sig_allocacmp_q_load = q_fu_48;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_83_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        q_out_ap_vld = 1'b1;
    end else begin
        q_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_132_p2 = (b_1_reg_212 + trunc_ln49_reg_231);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign b_2_fu_106_p4 = {{b_fu_44[30:1]}};

assign b_cast_fu_92_p1 = b_fu_44;

assign empty_38_fu_128_p1 = r_fu_40[30:0];

assign icmp_ln47_fu_83_p2 = ((b_fu_44 > 31'd64) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_136_p2 = ((r_fu_40 < t_reg_236) ? 1'b1 : 1'b0);

assign q_1_fu_153_p2 = (t_reg_236 + b_cast_reg_226);

assign q_2_fu_157_p3 = ((xor_ln50_fu_141_p2[0:0] == 1'b1) ? q_1_fu_153_p2 : q_load_reg_221);

assign q_out = q_fu_48;

assign r_1_fu_147_p2 = (empty_38_fu_128_p1 - add_ln43_fu_132_p2);

assign r_2_fu_169_p3 = {{select_ln50_fu_164_p3}, {1'd0}};

assign select_ln50_fu_164_p3 = ((xor_ln50_reg_247[0:0] == 1'b1) ? r_1_reg_252 : empty_38_reg_242);

assign t_fu_100_p2 = (b_cast_fu_92_p1 + ap_sig_allocacmp_q_load);

assign trunc_ln49_fu_96_p1 = ap_sig_allocacmp_q_load[30:0];

assign xor_ln50_fu_141_p2 = (icmp_ln50_fu_136_p2 ^ 1'd1);

assign zext_ln56_fu_116_p1 = b_2_fu_106_p4;

always @ (posedge ap_clk) begin
    b_cast_reg_226[31] <= 1'b0;
end

endmodule //rrt_rrt_Pipeline_VITIS_LOOP_47_12
