// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_FloatToFixed_16ul_s (
        ap_clk,
        ap_rst,
        d,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] d;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln7_fu_99_p2;
reg   [0:0] icmp_ln7_reg_267;
reg   [0:0] icmp_ln7_reg_267_pp0_iter1_reg;
reg   [0:0] icmp_ln7_reg_267_pp0_iter2_reg;
reg   [0:0] icmp_ln7_reg_267_pp0_iter3_reg;
reg   [0:0] icmp_ln7_reg_267_pp0_iter4_reg;
reg   [0:0] icmp_ln7_reg_267_pp0_iter5_reg;
wire   [0:0] icmp_ln7_2_fu_105_p2;
reg   [0:0] icmp_ln7_2_reg_272;
reg   [0:0] icmp_ln7_2_reg_272_pp0_iter1_reg;
reg   [0:0] icmp_ln7_2_reg_272_pp0_iter2_reg;
reg   [0:0] icmp_ln7_2_reg_272_pp0_iter3_reg;
reg   [0:0] icmp_ln7_2_reg_272_pp0_iter4_reg;
reg   [0:0] icmp_ln7_2_reg_272_pp0_iter5_reg;
wire   [0:0] grp_fu_71_p2;
reg   [0:0] tmp_5_reg_277;
reg   [0:0] tmp_5_reg_277_pp0_iter3_reg;
reg   [0:0] tmp_5_reg_277_pp0_iter4_reg;
reg   [0:0] tmp_5_reg_277_pp0_iter5_reg;
wire   [31:0] grp_fu_62_p2;
reg   [31:0] mul_reg_282;
wire   [63:0] grp_fu_68_p1;
reg   [63:0] conv_reg_287;
wire   [63:0] select_ln7_fu_120_p3;
reg   [63:0] select_ln7_reg_292;
wire   [63:0] grp_fu_77_p2;
reg   [63:0] dc_reg_297;
reg   [0:0] p_Result_s_reg_302;
reg   [0:0] p_Result_s_reg_302_pp0_iter20_reg;
wire   [51:0] tmp_56_fu_149_p1;
reg   [51:0] tmp_56_reg_307;
wire   [0:0] isNeg_fu_163_p3;
reg   [0:0] isNeg_reg_312;
wire   [11:0] ush_fu_181_p3;
reg   [11:0] ush_reg_317;
wire   [31:0] val_fu_243_p3;
reg   [31:0] val_reg_322;
wire    ap_block_pp0_stage0;
wire   [31:0] bitcast_ln7_fu_81_p1;
wire   [7:0] tmp_s_fu_85_p4;
wire   [22:0] trunc_ln7_fu_95_p1;
wire   [0:0] or_ln7_fu_111_p2;
wire   [0:0] and_ln7_fu_115_p2;
wire   [63:0] data_V_fu_128_p1;
wire   [10:0] tmp_55_fu_139_p4;
wire   [11:0] zext_ln513_fu_153_p1;
wire   [11:0] add_ln513_fu_157_p2;
wire   [10:0] sub_ln1364_fu_171_p2;
wire  signed [11:0] sext_ln1364_fu_177_p1;
wire   [53:0] mantissa_fu_189_p4;
wire  signed [31:0] sext_ln1340_fu_202_p1;
wire   [136:0] zext_ln15_fu_198_p1;
wire   [136:0] zext_ln1340_fu_205_p1;
wire   [136:0] r_V_fu_209_p2;
wire   [0:0] tmp_fu_221_p3;
wire   [136:0] r_V_15_fu_215_p2;
wire   [31:0] zext_ln671_fu_229_p1;
wire   [31:0] tmp_10_fu_233_p4;
wire   [31:0] result_V_29_fu_250_p2;
reg    grp_fu_62_ce;
reg    grp_fu_68_ce;
reg    grp_fu_71_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_77_ce;
wire   [31:0] result_V_fu_255_p3;
reg    ap_ce_reg;
reg   [31:0] d_int_reg;
reg   [31:0] ap_return_int_reg;

rrt_fmul_32ns_32ns_32_5_max_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_5_max_dsp_0_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d_int_reg),
    .din1(32'd1199570944),
    .ce(grp_fu_62_ce),
    .dout(grp_fu_62_p2)
);

rrt_fpext_32ns_64_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_0_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_282),
    .ce(grp_fu_68_ce),
    .dout(grp_fu_68_p1)
);

rrt_fcmp_32ns_32ns_1_3_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_3_no_dsp_0_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d_int_reg),
    .din1(32'd0),
    .ce(grp_fu_71_ce),
    .opcode(5'd3),
    .dout(grp_fu_71_p2)
);

rrt_dadd_64ns_64ns_64_12_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_12_full_dsp_0_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_reg_287),
    .din1(select_ln7_reg_292),
    .ce(grp_fu_77_ce),
    .dout(grp_fu_77_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= result_V_fu_255_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        conv_reg_287 <= grp_fu_68_p1;
        dc_reg_297 <= grp_fu_77_p2;
        icmp_ln7_2_reg_272 <= icmp_ln7_2_fu_105_p2;
        icmp_ln7_2_reg_272_pp0_iter1_reg <= icmp_ln7_2_reg_272;
        icmp_ln7_2_reg_272_pp0_iter2_reg <= icmp_ln7_2_reg_272_pp0_iter1_reg;
        icmp_ln7_2_reg_272_pp0_iter3_reg <= icmp_ln7_2_reg_272_pp0_iter2_reg;
        icmp_ln7_2_reg_272_pp0_iter4_reg <= icmp_ln7_2_reg_272_pp0_iter3_reg;
        icmp_ln7_2_reg_272_pp0_iter5_reg <= icmp_ln7_2_reg_272_pp0_iter4_reg;
        icmp_ln7_reg_267 <= icmp_ln7_fu_99_p2;
        icmp_ln7_reg_267_pp0_iter1_reg <= icmp_ln7_reg_267;
        icmp_ln7_reg_267_pp0_iter2_reg <= icmp_ln7_reg_267_pp0_iter1_reg;
        icmp_ln7_reg_267_pp0_iter3_reg <= icmp_ln7_reg_267_pp0_iter2_reg;
        icmp_ln7_reg_267_pp0_iter4_reg <= icmp_ln7_reg_267_pp0_iter3_reg;
        icmp_ln7_reg_267_pp0_iter5_reg <= icmp_ln7_reg_267_pp0_iter4_reg;
        isNeg_reg_312 <= add_ln513_fu_157_p2[32'd11];
        mul_reg_282 <= grp_fu_62_p2;
        p_Result_s_reg_302 <= data_V_fu_128_p1[32'd63];
        p_Result_s_reg_302_pp0_iter20_reg <= p_Result_s_reg_302;
        select_ln7_reg_292[63] <= select_ln7_fu_120_p3[63];
        tmp_56_reg_307 <= tmp_56_fu_149_p1;
        tmp_5_reg_277 <= grp_fu_71_p2;
        tmp_5_reg_277_pp0_iter3_reg <= tmp_5_reg_277;
        tmp_5_reg_277_pp0_iter4_reg <= tmp_5_reg_277_pp0_iter3_reg;
        tmp_5_reg_277_pp0_iter5_reg <= tmp_5_reg_277_pp0_iter4_reg;
        ush_reg_317 <= ush_fu_181_p3;
        val_reg_322 <= val_fu_243_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        d_int_reg <= d;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = result_V_fu_255_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_62_ce = 1'b1;
    end else begin
        grp_fu_62_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_68_ce = 1'b1;
    end else begin
        grp_fu_68_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_71_ce = 1'b1;
    end else begin
        grp_fu_71_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_77_ce = 1'b1;
    end else begin
        grp_fu_77_ce = 1'b0;
    end
end

assign add_ln513_fu_157_p2 = ($signed(zext_ln513_fu_153_p1) + $signed(12'd3073));

assign and_ln7_fu_115_p2 = (tmp_5_reg_277_pp0_iter5_reg & or_ln7_fu_111_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign bitcast_ln7_fu_81_p1 = d_int_reg;

assign data_V_fu_128_p1 = dc_reg_297;

assign icmp_ln7_2_fu_105_p2 = ((trunc_ln7_fu_95_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_99_p2 = ((tmp_s_fu_85_p4 != 8'd255) ? 1'b1 : 1'b0);

assign isNeg_fu_163_p3 = add_ln513_fu_157_p2[32'd11];

assign mantissa_fu_189_p4 = {{{{1'd1}, {tmp_56_reg_307}}}, {1'd0}};

assign or_ln7_fu_111_p2 = (icmp_ln7_reg_267_pp0_iter5_reg | icmp_ln7_2_reg_272_pp0_iter5_reg);

assign r_V_15_fu_215_p2 = zext_ln15_fu_198_p1 << zext_ln1340_fu_205_p1;

assign r_V_fu_209_p2 = zext_ln15_fu_198_p1 >> zext_ln1340_fu_205_p1;

assign result_V_29_fu_250_p2 = (32'd0 - val_reg_322);

assign result_V_fu_255_p3 = ((p_Result_s_reg_302_pp0_iter20_reg[0:0] == 1'b1) ? result_V_29_fu_250_p2 : val_reg_322);

assign select_ln7_fu_120_p3 = ((and_ln7_fu_115_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign sext_ln1340_fu_202_p1 = $signed(ush_reg_317);

assign sext_ln1364_fu_177_p1 = $signed(sub_ln1364_fu_171_p2);

assign sub_ln1364_fu_171_p2 = (11'd1023 - tmp_55_fu_139_p4);

assign tmp_10_fu_233_p4 = {{r_V_15_fu_215_p2[84:53]}};

assign tmp_55_fu_139_p4 = {{data_V_fu_128_p1[62:52]}};

assign tmp_56_fu_149_p1 = data_V_fu_128_p1[51:0];

assign tmp_fu_221_p3 = r_V_fu_209_p2[32'd53];

assign tmp_s_fu_85_p4 = {{bitcast_ln7_fu_81_p1[30:23]}};

assign trunc_ln7_fu_95_p1 = bitcast_ln7_fu_81_p1[22:0];

assign ush_fu_181_p3 = ((isNeg_fu_163_p3[0:0] == 1'b1) ? sext_ln1364_fu_177_p1 : add_ln513_fu_157_p2);

assign val_fu_243_p3 = ((isNeg_reg_312[0:0] == 1'b1) ? zext_ln671_fu_229_p1 : tmp_10_fu_233_p4);

assign zext_ln1340_fu_205_p1 = $unsigned(sext_ln1340_fu_202_p1);

assign zext_ln15_fu_198_p1 = mantissa_fu_189_p4;

assign zext_ln513_fu_153_p1 = tmp_55_fu_139_p4;

assign zext_ln671_fu_229_p1 = tmp_fu_221_p3;

always @ (posedge ap_clk) begin
    select_ln7_reg_292[62:0] <= 63'b011111111100000000000000000000000000000000000000000000000000000;
end

endmodule //rrt_FloatToFixed_16ul_s
