// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rrt_Nearhw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        X_near_address0,
        X_near_ce0,
        X_near_we0,
        X_near_d0,
        RRT_Star_Pos_0_0_address0,
        RRT_Star_Pos_0_0_ce0,
        RRT_Star_Pos_0_0_q0,
        RRT_Star_Pos_0_1_address0,
        RRT_Star_Pos_0_1_ce0,
        RRT_Star_Pos_0_1_q0,
        RRT_Star_Pos_1_address0,
        RRT_Star_Pos_1_ce0,
        RRT_Star_Pos_1_q0,
        p_read,
        p_read1,
        Squared_r_n,
        N,
        ap_return,
        grp_fu_537_p_din0,
        grp_fu_537_p_din1,
        grp_fu_537_p_opcode,
        grp_fu_537_p_dout0,
        grp_fu_537_p_ce,
        grp_fu_541_p_din0,
        grp_fu_541_p_din1,
        grp_fu_541_p_opcode,
        grp_fu_541_p_dout0,
        grp_fu_541_p_ce,
        grp_fu_550_p_din0,
        grp_fu_550_p_dout0,
        grp_fu_550_p_ce,
        grp_fu_553_p_din0,
        grp_fu_553_p_dout0,
        grp_fu_553_p_ce,
        grp_fu_1261_p_din0,
        grp_fu_1261_p_din1,
        grp_fu_1261_p_dout0,
        grp_fu_1261_p_ce,
        grp_fu_1271_p_din0,
        grp_fu_1271_p_din1,
        grp_fu_1271_p_dout0,
        grp_fu_1271_p_ce
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state38 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] X_near_address0;
output   X_near_ce0;
output   X_near_we0;
output  [15:0] X_near_d0;
output  [13:0] RRT_Star_Pos_0_0_address0;
output   RRT_Star_Pos_0_0_ce0;
input  [31:0] RRT_Star_Pos_0_0_q0;
output  [13:0] RRT_Star_Pos_0_1_address0;
output   RRT_Star_Pos_0_1_ce0;
input  [31:0] RRT_Star_Pos_0_1_q0;
output  [13:0] RRT_Star_Pos_1_address0;
output   RRT_Star_Pos_1_ce0;
input  [15:0] RRT_Star_Pos_1_q0;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] Squared_r_n;
input  [13:0] N;
output  [31:0] ap_return;
output  [31:0] grp_fu_537_p_din0;
output  [31:0] grp_fu_537_p_din1;
output  [1:0] grp_fu_537_p_opcode;
input  [31:0] grp_fu_537_p_dout0;
output   grp_fu_537_p_ce;
output  [31:0] grp_fu_541_p_din0;
output  [31:0] grp_fu_541_p_din1;
output  [1:0] grp_fu_541_p_opcode;
input  [31:0] grp_fu_541_p_dout0;
output   grp_fu_541_p_ce;
output  [31:0] grp_fu_550_p_din0;
input  [31:0] grp_fu_550_p_dout0;
output   grp_fu_550_p_ce;
output  [31:0] grp_fu_553_p_din0;
input  [31:0] grp_fu_553_p_dout0;
output   grp_fu_553_p_ce;
output  [31:0] grp_fu_1261_p_din0;
output  [31:0] grp_fu_1261_p_din1;
input  [47:0] grp_fu_1261_p_dout0;
output   grp_fu_1261_p_ce;
output  [31:0] grp_fu_1271_p_din0;
output  [31:0] grp_fu_1271_p_din1;
input  [47:0] grp_fu_1271_p_dout0;
output   grp_fu_1271_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg X_near_ce0;
reg X_near_we0;
reg RRT_Star_Pos_0_0_ce0;
reg RRT_Star_Pos_0_1_ce0;
reg RRT_Star_Pos_1_ce0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state7;
reg   [31:0] conv_i_i_reg_602;
reg   [31:0] conv9_i_i_reg_607;
wire   [63:0] i_cast_fu_211_p1;
reg   [63:0] i_cast_reg_615;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    ap_block_state11_pp0_stage0_iter3;
wire    ap_block_state12_pp0_stage0_iter4;
wire    ap_block_state13_pp0_stage0_iter5;
wire    ap_block_state14_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state16_pp0_stage0_iter8;
wire    ap_block_state17_pp0_stage0_iter9;
wire    ap_block_state18_pp0_stage0_iter10;
wire    ap_block_state19_pp0_stage0_iter11;
wire    ap_block_state20_pp0_stage0_iter12;
wire    ap_block_state21_pp0_stage0_iter13;
wire    ap_block_state22_pp0_stage0_iter14;
wire    ap_block_state23_pp0_stage0_iter15;
wire    ap_block_state24_pp0_stage0_iter16;
wire    ap_block_state25_pp0_stage0_iter17;
wire    ap_block_state26_pp0_stage0_iter18;
wire    ap_block_state27_pp0_stage0_iter19;
wire    ap_block_state28_pp0_stage0_iter20;
wire    ap_block_state29_pp0_stage0_iter21;
wire    ap_block_state30_pp0_stage0_iter22;
wire    ap_block_state31_pp0_stage0_iter23;
wire    ap_block_state32_pp0_stage0_iter24;
wire    ap_block_state33_pp0_stage0_iter25;
wire    ap_block_state34_pp0_stage0_iter26;
wire    ap_block_state35_pp0_stage0_iter27;
wire    ap_block_state36_pp0_stage0_iter28;
wire    ap_block_state37_pp0_stage0_iter29;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln141_fu_200_p2;
reg   [63:0] i_cast_reg_615_pp0_iter1_reg;
reg   [63:0] i_cast_reg_615_pp0_iter2_reg;
reg   [63:0] i_cast_reg_615_pp0_iter3_reg;
reg   [63:0] i_cast_reg_615_pp0_iter4_reg;
reg   [63:0] i_cast_reg_615_pp0_iter5_reg;
reg   [63:0] i_cast_reg_615_pp0_iter6_reg;
reg   [63:0] i_cast_reg_615_pp0_iter7_reg;
reg   [63:0] i_cast_reg_615_pp0_iter8_reg;
reg   [63:0] i_cast_reg_615_pp0_iter9_reg;
reg   [63:0] i_cast_reg_615_pp0_iter10_reg;
reg   [63:0] i_cast_reg_615_pp0_iter11_reg;
reg   [63:0] i_cast_reg_615_pp0_iter12_reg;
reg   [63:0] i_cast_reg_615_pp0_iter13_reg;
reg   [63:0] i_cast_reg_615_pp0_iter14_reg;
reg   [63:0] i_cast_reg_615_pp0_iter15_reg;
reg   [63:0] i_cast_reg_615_pp0_iter16_reg;
reg   [63:0] i_cast_reg_615_pp0_iter17_reg;
reg   [63:0] i_cast_reg_615_pp0_iter18_reg;
reg   [63:0] i_cast_reg_615_pp0_iter19_reg;
reg   [63:0] i_cast_reg_615_pp0_iter20_reg;
reg   [63:0] i_cast_reg_615_pp0_iter21_reg;
reg   [63:0] i_cast_reg_615_pp0_iter22_reg;
reg   [63:0] i_cast_reg_615_pp0_iter23_reg;
reg   [63:0] i_cast_reg_615_pp0_iter24_reg;
reg   [63:0] i_cast_reg_615_pp0_iter25_reg;
reg   [63:0] i_cast_reg_615_pp0_iter26_reg;
reg   [31:0] B_x_reg_630;
reg   [31:0] B_y_reg_635;
reg   [31:0] conv_i_i_i_reg_640;
reg    ap_enable_reg_pp0_iter8;
reg   [31:0] conv_i2_i_i_reg_645;
reg   [31:0] dc_reg_650;
reg   [31:0] dc_3_reg_655;
reg   [0:0] p_Result_s_reg_660;
reg   [0:0] p_Result_s_reg_660_pp0_iter19_reg;
wire   [22:0] tmp_41_fu_243_p1;
reg   [22:0] tmp_41_reg_665;
wire   [0:0] isNeg_fu_257_p3;
reg   [0:0] isNeg_reg_670;
wire   [8:0] ush_fu_275_p3;
reg   [8:0] ush_reg_675;
reg   [0:0] p_Result_3_reg_680;
reg   [0:0] p_Result_3_reg_680_pp0_iter19_reg;
wire   [22:0] tmp_43_fu_304_p1;
reg   [22:0] tmp_43_reg_685;
wire   [0:0] isNeg_3_fu_318_p3;
reg   [0:0] isNeg_3_reg_690;
wire   [8:0] ush_3_fu_336_p3;
reg   [8:0] ush_3_reg_695;
wire   [31:0] val_fu_398_p3;
reg   [31:0] val_reg_700;
wire   [31:0] val_3_fu_459_p3;
reg   [31:0] val_3_reg_706;
wire   [31:0] result_V_fu_471_p3;
reg   [31:0] result_V_reg_712;
wire   [31:0] result_V_21_fu_482_p3;
reg   [31:0] result_V_21_reg_717;
wire  signed [47:0] sext_ln34_fu_488_p1;
wire  signed [47:0] sext_ln34_6_fu_497_p1;
reg   [31:0] trunc_ln_reg_734;
reg   [31:0] trunc_ln34_4_reg_739;
wire   [31:0] D_fu_526_p2;
reg   [31:0] D_reg_744;
wire   [0:0] icmp_ln149_fu_530_p2;
reg   [0:0] icmp_ln149_reg_749;
reg   [0:0] icmp_ln149_reg_749_pp0_iter28_reg;
reg   [15:0] RRT_Star_Pos_1_load_reg_758;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln151_fu_537_p1;
reg   [13:0] i_fu_78;
wire   [13:0] add_ln141_fu_205_p2;
reg   [31:0] empty_fu_82;
wire   [31:0] add_ln152_fu_542_p2;
reg   [31:0] X_near_count_0_fu_86;
wire    ap_CS_fsm_state38;
reg   [31:0] grp_fu_174_p0;
reg   [31:0] grp_fu_178_p0;
wire   [31:0] data_V_fu_222_p1;
wire   [7:0] tmp_40_fu_233_p4;
wire   [8:0] zext_ln344_fu_247_p1;
wire   [8:0] add_ln344_fu_251_p2;
wire   [7:0] sub_ln1364_fu_265_p2;
wire  signed [8:0] sext_ln1364_fu_271_p1;
wire   [31:0] data_V_3_fu_283_p1;
wire   [7:0] tmp_42_fu_294_p4;
wire   [8:0] zext_ln344_2_fu_308_p1;
wire   [8:0] add_ln344_2_fu_312_p2;
wire   [7:0] sub_ln1364_2_fu_326_p2;
wire  signed [8:0] sext_ln1364_2_fu_332_p1;
wire   [24:0] mantissa_fu_344_p4;
wire  signed [31:0] sext_ln1340_fu_357_p1;
wire   [78:0] zext_ln15_fu_353_p1;
wire   [78:0] zext_ln1340_fu_360_p1;
wire   [78:0] r_V_fu_364_p2;
wire   [0:0] tmp_fu_376_p3;
wire   [78:0] r_V_9_fu_370_p2;
wire   [31:0] zext_ln671_fu_384_p1;
wire   [31:0] tmp_s_fu_388_p4;
wire   [24:0] mantissa_2_fu_405_p4;
wire  signed [31:0] sext_ln1340_3_fu_418_p1;
wire   [78:0] zext_ln15_2_fu_414_p1;
wire   [78:0] zext_ln1340_3_fu_421_p1;
wire   [78:0] r_V_10_fu_425_p2;
wire   [0:0] tmp_39_fu_437_p3;
wire   [78:0] r_V_11_fu_431_p2;
wire   [31:0] zext_ln671_2_fu_445_p1;
wire   [31:0] tmp_6_fu_449_p4;
wire   [31:0] result_V_17_fu_466_p2;
wire   [31:0] result_V_20_fu_477_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state38_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state8)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter29 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        X_near_count_0_fu_86 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter29 == 1'b1) & (icmp_ln149_reg_749_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        X_near_count_0_fu_86 <= add_ln152_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        empty_fu_82 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter29 == 1'b1) & (icmp_ln149_reg_749_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_fu_82 <= add_ln152_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_78 <= 14'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln141_fu_200_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_fu_78 <= add_ln141_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_x_reg_630 <= RRT_Star_Pos_0_0_q0;
        B_y_reg_635 <= RRT_Star_Pos_0_1_q0;
        i_cast_reg_615_pp0_iter1_reg[13 : 0] <= i_cast_reg_615[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        D_reg_744 <= D_fu_526_p2;
        dc_3_reg_655 <= grp_fu_541_p_dout0;
        dc_reg_650 <= grp_fu_537_p_dout0;
        i_cast_reg_615_pp0_iter10_reg[13 : 0] <= i_cast_reg_615_pp0_iter9_reg[13 : 0];
        i_cast_reg_615_pp0_iter11_reg[13 : 0] <= i_cast_reg_615_pp0_iter10_reg[13 : 0];
        i_cast_reg_615_pp0_iter12_reg[13 : 0] <= i_cast_reg_615_pp0_iter11_reg[13 : 0];
        i_cast_reg_615_pp0_iter13_reg[13 : 0] <= i_cast_reg_615_pp0_iter12_reg[13 : 0];
        i_cast_reg_615_pp0_iter14_reg[13 : 0] <= i_cast_reg_615_pp0_iter13_reg[13 : 0];
        i_cast_reg_615_pp0_iter15_reg[13 : 0] <= i_cast_reg_615_pp0_iter14_reg[13 : 0];
        i_cast_reg_615_pp0_iter16_reg[13 : 0] <= i_cast_reg_615_pp0_iter15_reg[13 : 0];
        i_cast_reg_615_pp0_iter17_reg[13 : 0] <= i_cast_reg_615_pp0_iter16_reg[13 : 0];
        i_cast_reg_615_pp0_iter18_reg[13 : 0] <= i_cast_reg_615_pp0_iter17_reg[13 : 0];
        i_cast_reg_615_pp0_iter19_reg[13 : 0] <= i_cast_reg_615_pp0_iter18_reg[13 : 0];
        i_cast_reg_615_pp0_iter20_reg[13 : 0] <= i_cast_reg_615_pp0_iter19_reg[13 : 0];
        i_cast_reg_615_pp0_iter21_reg[13 : 0] <= i_cast_reg_615_pp0_iter20_reg[13 : 0];
        i_cast_reg_615_pp0_iter22_reg[13 : 0] <= i_cast_reg_615_pp0_iter21_reg[13 : 0];
        i_cast_reg_615_pp0_iter23_reg[13 : 0] <= i_cast_reg_615_pp0_iter22_reg[13 : 0];
        i_cast_reg_615_pp0_iter24_reg[13 : 0] <= i_cast_reg_615_pp0_iter23_reg[13 : 0];
        i_cast_reg_615_pp0_iter25_reg[13 : 0] <= i_cast_reg_615_pp0_iter24_reg[13 : 0];
        i_cast_reg_615_pp0_iter26_reg[13 : 0] <= i_cast_reg_615_pp0_iter25_reg[13 : 0];
        i_cast_reg_615_pp0_iter2_reg[13 : 0] <= i_cast_reg_615_pp0_iter1_reg[13 : 0];
        i_cast_reg_615_pp0_iter3_reg[13 : 0] <= i_cast_reg_615_pp0_iter2_reg[13 : 0];
        i_cast_reg_615_pp0_iter4_reg[13 : 0] <= i_cast_reg_615_pp0_iter3_reg[13 : 0];
        i_cast_reg_615_pp0_iter5_reg[13 : 0] <= i_cast_reg_615_pp0_iter4_reg[13 : 0];
        i_cast_reg_615_pp0_iter6_reg[13 : 0] <= i_cast_reg_615_pp0_iter5_reg[13 : 0];
        i_cast_reg_615_pp0_iter7_reg[13 : 0] <= i_cast_reg_615_pp0_iter6_reg[13 : 0];
        i_cast_reg_615_pp0_iter8_reg[13 : 0] <= i_cast_reg_615_pp0_iter7_reg[13 : 0];
        i_cast_reg_615_pp0_iter9_reg[13 : 0] <= i_cast_reg_615_pp0_iter8_reg[13 : 0];
        icmp_ln149_reg_749 <= icmp_ln149_fu_530_p2;
        icmp_ln149_reg_749_pp0_iter28_reg <= icmp_ln149_reg_749;
        isNeg_3_reg_690 <= add_ln344_2_fu_312_p2[32'd8];
        isNeg_reg_670 <= add_ln344_fu_251_p2[32'd8];
        p_Result_3_reg_680 <= data_V_3_fu_283_p1[32'd31];
        p_Result_3_reg_680_pp0_iter19_reg <= p_Result_3_reg_680;
        p_Result_s_reg_660 <= data_V_fu_222_p1[32'd31];
        p_Result_s_reg_660_pp0_iter19_reg <= p_Result_s_reg_660;
        result_V_21_reg_717 <= result_V_21_fu_482_p3;
        result_V_reg_712 <= result_V_fu_471_p3;
        tmp_41_reg_665 <= tmp_41_fu_243_p1;
        tmp_43_reg_685 <= tmp_43_fu_304_p1;
        trunc_ln34_4_reg_739 <= {{grp_fu_1271_p_dout0[47:16]}};
        trunc_ln_reg_734 <= {{grp_fu_1261_p_dout0[47:16]}};
        ush_3_reg_695 <= ush_3_fu_336_p3;
        ush_reg_675 <= ush_fu_275_p3;
        val_3_reg_706 <= val_3_fu_459_p3;
        val_reg_700 <= val_fu_398_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln149_reg_749 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Pos_1_load_reg_758 <= RRT_Star_Pos_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        conv9_i_i_reg_607 <= grp_fu_553_p_dout0;
        conv_i_i_reg_602 <= grp_fu_550_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_i2_i_i_reg_645 <= grp_fu_553_p_dout0;
        conv_i_i_i_reg_640 <= grp_fu_550_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln141_fu_200_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_cast_reg_615[13 : 0] <= i_cast_fu_211_p1[13 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Pos_0_0_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Pos_0_1_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        RRT_Star_Pos_1_ce0 = 1'b1;
    end else begin
        RRT_Star_Pos_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter29 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        X_near_ce0 = 1'b1;
    end else begin
        X_near_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter29 == 1'b1) & (icmp_ln149_reg_749_pp0_iter28_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        X_near_we0 = 1'b1;
    end else begin
        X_near_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln141_fu_200_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_174_p0 = B_x_reg_630;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_174_p0 = p_read;
    end else begin
        grp_fu_174_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_178_p0 = B_y_reg_635;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_178_p0 = p_read1;
    end else begin
        grp_fu_178_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln141_fu_200_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter29 == 1'b1) & (ap_enable_reg_pp0_iter28 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter29 == 1'b1) & (ap_enable_reg_pp0_iter28 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln141_fu_200_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D_fu_526_p2 = (trunc_ln34_4_reg_739 + trunc_ln_reg_734);

assign RRT_Star_Pos_0_0_address0 = i_cast_fu_211_p1;

assign RRT_Star_Pos_0_1_address0 = i_cast_fu_211_p1;

assign RRT_Star_Pos_1_address0 = i_cast_reg_615_pp0_iter26_reg;

assign X_near_address0 = zext_ln151_fu_537_p1;

assign X_near_d0 = RRT_Star_Pos_1_load_reg_758;

assign add_ln141_fu_205_p2 = (i_fu_78 + 14'd1);

assign add_ln152_fu_542_p2 = (empty_fu_82 + 32'd1);

assign add_ln344_2_fu_312_p2 = ($signed(zext_ln344_2_fu_308_p1) + $signed(9'd385));

assign add_ln344_fu_251_p2 = ($signed(zext_ln344_fu_247_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = X_near_count_0_fu_86;

assign data_V_3_fu_283_p1 = dc_3_reg_655;

assign data_V_fu_222_p1 = dc_reg_650;

assign grp_fu_1261_p_ce = 1'b1;

assign grp_fu_1261_p_din0 = sext_ln34_fu_488_p1;

assign grp_fu_1261_p_din1 = sext_ln34_fu_488_p1;

assign grp_fu_1271_p_ce = 1'b1;

assign grp_fu_1271_p_din0 = sext_ln34_6_fu_497_p1;

assign grp_fu_1271_p_din1 = sext_ln34_6_fu_497_p1;

assign grp_fu_537_p_ce = 1'b1;

assign grp_fu_537_p_din0 = conv_i_i_reg_602;

assign grp_fu_537_p_din1 = conv_i_i_i_reg_640;

assign grp_fu_537_p_opcode = 2'd1;

assign grp_fu_541_p_ce = 1'b1;

assign grp_fu_541_p_din0 = conv9_i_i_reg_607;

assign grp_fu_541_p_din1 = conv_i2_i_i_reg_645;

assign grp_fu_541_p_opcode = 2'd1;

assign grp_fu_550_p_ce = 1'b1;

assign grp_fu_550_p_din0 = grp_fu_174_p0;

assign grp_fu_553_p_ce = 1'b1;

assign grp_fu_553_p_din0 = grp_fu_178_p0;

assign i_cast_fu_211_p1 = i_fu_78;

assign icmp_ln141_fu_200_p2 = ((i_fu_78 == N) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_530_p2 = (($signed(D_reg_744) < $signed(Squared_r_n)) ? 1'b1 : 1'b0);

assign isNeg_3_fu_318_p3 = add_ln344_2_fu_312_p2[32'd8];

assign isNeg_fu_257_p3 = add_ln344_fu_251_p2[32'd8];

assign mantissa_2_fu_405_p4 = {{{{1'd1}, {tmp_43_reg_685}}}, {1'd0}};

assign mantissa_fu_344_p4 = {{{{1'd1}, {tmp_41_reg_665}}}, {1'd0}};

assign r_V_10_fu_425_p2 = zext_ln15_2_fu_414_p1 >> zext_ln1340_3_fu_421_p1;

assign r_V_11_fu_431_p2 = zext_ln15_2_fu_414_p1 << zext_ln1340_3_fu_421_p1;

assign r_V_9_fu_370_p2 = zext_ln15_fu_353_p1 << zext_ln1340_fu_360_p1;

assign r_V_fu_364_p2 = zext_ln15_fu_353_p1 >> zext_ln1340_fu_360_p1;

assign result_V_17_fu_466_p2 = (32'd0 - val_reg_700);

assign result_V_20_fu_477_p2 = (32'd0 - val_3_reg_706);

assign result_V_21_fu_482_p3 = ((p_Result_3_reg_680_pp0_iter19_reg[0:0] == 1'b1) ? result_V_20_fu_477_p2 : val_3_reg_706);

assign result_V_fu_471_p3 = ((p_Result_s_reg_660_pp0_iter19_reg[0:0] == 1'b1) ? result_V_17_fu_466_p2 : val_reg_700);

assign sext_ln1340_3_fu_418_p1 = $signed(ush_3_reg_695);

assign sext_ln1340_fu_357_p1 = $signed(ush_reg_675);

assign sext_ln1364_2_fu_332_p1 = $signed(sub_ln1364_2_fu_326_p2);

assign sext_ln1364_fu_271_p1 = $signed(sub_ln1364_fu_265_p2);

assign sext_ln34_6_fu_497_p1 = $signed(result_V_21_reg_717);

assign sext_ln34_fu_488_p1 = $signed(result_V_reg_712);

assign sub_ln1364_2_fu_326_p2 = (8'd127 - tmp_42_fu_294_p4);

assign sub_ln1364_fu_265_p2 = (8'd127 - tmp_40_fu_233_p4);

assign tmp_39_fu_437_p3 = r_V_10_fu_425_p2[32'd24];

assign tmp_40_fu_233_p4 = {{data_V_fu_222_p1[30:23]}};

assign tmp_41_fu_243_p1 = data_V_fu_222_p1[22:0];

assign tmp_42_fu_294_p4 = {{data_V_3_fu_283_p1[30:23]}};

assign tmp_43_fu_304_p1 = data_V_3_fu_283_p1[22:0];

assign tmp_6_fu_449_p4 = {{r_V_11_fu_431_p2[55:24]}};

assign tmp_fu_376_p3 = r_V_fu_364_p2[32'd24];

assign tmp_s_fu_388_p4 = {{r_V_9_fu_370_p2[55:24]}};

assign ush_3_fu_336_p3 = ((isNeg_3_fu_318_p3[0:0] == 1'b1) ? sext_ln1364_2_fu_332_p1 : add_ln344_2_fu_312_p2);

assign ush_fu_275_p3 = ((isNeg_fu_257_p3[0:0] == 1'b1) ? sext_ln1364_fu_271_p1 : add_ln344_fu_251_p2);

assign val_3_fu_459_p3 = ((isNeg_3_reg_690[0:0] == 1'b1) ? zext_ln671_2_fu_445_p1 : tmp_6_fu_449_p4);

assign val_fu_398_p3 = ((isNeg_reg_670[0:0] == 1'b1) ? zext_ln671_fu_384_p1 : tmp_s_fu_388_p4);

assign zext_ln1340_3_fu_421_p1 = $unsigned(sext_ln1340_3_fu_418_p1);

assign zext_ln1340_fu_360_p1 = $unsigned(sext_ln1340_fu_357_p1);

assign zext_ln151_fu_537_p1 = empty_fu_82;

assign zext_ln15_2_fu_414_p1 = mantissa_2_fu_405_p4;

assign zext_ln15_fu_353_p1 = mantissa_fu_344_p4;

assign zext_ln344_2_fu_308_p1 = tmp_42_fu_294_p4;

assign zext_ln344_fu_247_p1 = tmp_40_fu_233_p4;

assign zext_ln671_2_fu_445_p1 = tmp_39_fu_437_p3;

assign zext_ln671_fu_384_p1 = tmp_fu_376_p3;

always @ (posedge ap_clk) begin
    i_cast_reg_615[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter4_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter5_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter6_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter7_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter8_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter9_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter10_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter11_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter12_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter13_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter14_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter15_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter16_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter17_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter18_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter19_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter20_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter21_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter22_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter23_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter24_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter25_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    i_cast_reg_615_pp0_iter26_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //rrt_Nearhw
