
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrrt.h"

/*
* The configuration table for devices
*/

XRrt_Config XRrt_ConfigTable[XPAR_XRRT_NUM_INSTANCES] =
{
	{
		XPAR_RRT_0_DEVICE_ID,
		XPAR_RRT_0_S_AXI_CTRL_BUS_BASEADDR
	}
};


